// Auto-generated by scripts/generate-types.js — do not edit manually
// Generated from 315 UBX message definitions

export interface NavPosecef {
  name: "NAV-POSECEF";
  iTOW: number;
  ecefX: number;
  ecefY: number;
  ecefZ: number;
  pAcc: number;
}
export interface NavPosecefPoll {
  name: "NAV-POSECEF";
  variant: "Poll";
}
export interface NavPosllh {
  name: "NAV-POSLLH";
  iTOW: number;
  lon: number;
  lat: number;
  height: number;
  hMSL: number;
  hAcc: number;
  vAcc: number;
}
export interface NavPosllhPoll {
  name: "NAV-POSLLH";
  variant: "Poll";
}
export interface NavStatus {
  name: "NAV-STATUS";
  iTOW: number;
  gpsFix: number;
  flags: number;
  fixStat: {
    diffCorr: boolean;
    carrSolnValid: boolean;
    mapMatching: number;
  };
  flags2: {
    psmState: number;
    res1: number;
    spoofDetState: number;
    res2: number;
    carrSoln: number;
  };
  ttff: number;
  msss: number;
}
export interface NavStatusPoll {
  name: "NAV-STATUS";
  variant: "Poll";
}
export interface NavDop {
  name: "NAV-DOP";
  iTOW: number;
  gDOP: number;
  pDOP: number;
  tDOP: number;
  vDOP: number;
  hDOP: number;
  nDOP: number;
  eDOP: number;
}
export interface NavDopPoll {
  name: "NAV-DOP";
  variant: "Poll";
}
export interface NavAtt {
  name: "NAV-ATT";
  iTOW: number;
  version: number;
  reserved1: number;
  roll: number;
  pitch: number;
  heading: number;
  accRoll: number;
  accPitch: number;
  accHeading: number;
}
export interface NavAttPoll {
  name: "NAV-ATT";
  variant: "Poll";
}
export interface NavSol {
  name: "NAV-SOL";
  iTOW: number;
  fTOW: number;
  week: number;
  gpsFix: number;
  flags: number;
  ecefX: number;
  ecefY: number;
  ecefZ: number;
  pAcc: number;
  ecefVX: number;
  ecefVY: number;
  ecefVZ: number;
  sAcc: number;
  pDOP: number;
  reserved1: number;
  numSV: number;
  reserved2: number;
}
export interface NavSolPoll {
  name: "NAV-SOL";
  variant: "Poll";
}
export interface NavPvtUblox89 {
  name: "NAV-PVT";
  variant: "ublox-8/9";
  iTOW: number;
  year: number;
  month: number;
  day: number;
  hour: number;
  min: number;
  sec: number;
  valid: number;
  tAcc: number;
  nano: number;
  fixType: number;
  flags: {
    gnssFixOK: boolean;
    diffSoln: boolean;
    psmState: number;
    headVehValid: boolean;
    carrSoln: number;
  };
  flags2: number;
  numSV: number;
  lon: number;
  lat: number;
  height: number;
  hMSL: number;
  hAcc: number;
  vAcc: number;
  velN: number;
  velE: number;
  velD: number;
  gSpeed: number;
  heading: number;
  sAcc: number;
  headingAcc: number;
  pDop: number;
  flags3: number;
  reserved2: number;
  reserved3: number;
  headVeh: number;
  magDec: number;
  magAcc: number;
}
export interface NavPvt {
  name: "NAV-PVT";
  iTOW: number;
  year: number;
  month: number;
  day: number;
  hour: number;
  min: number;
  sec: number;
  valid: number;
  tAcc: number;
  nano: number;
  fixType: number;
  flags: {
    gnssFixOK: boolean;
    diffSoln: boolean;
    psmState: number;
    headVehValid: boolean;
    carrSoln: number;
  };
  flags2: number;
  numSV: number;
  lon: number;
  lat: number;
  height: number;
  hMSL: number;
  hAcc: number;
  vAcc: number;
  velN: number;
  velE: number;
  velD: number;
  gSpeed: number;
  heading: number;
  sAcc: number;
  headingAcc: number;
  pDop: number;
  flags3: number;
  reserved2: number;
  reserved3: number;
}
export interface NavPvtPoll {
  name: "NAV-PVT";
  variant: "Poll";
}
export interface NavOdo {
  name: "NAV-ODO";
  version: number;
  reserved1: number;
  iTOW: number;
  distance: number;
  totalDistance: number;
  distanceStd: number;
}
export interface NavOdoPoll {
  name: "NAV-ODO";
  variant: "Poll";
}
export interface NavResetodo {
  name: "NAV-RESETODO";
}
export interface NavVelecef {
  name: "NAV-VELECEF";
  iTOW: number;
  ecefVX: number;
  ecefVY: number;
  ecefVZ: number;
  sAcc: number;
}
export interface NavVelecefPoll {
  name: "NAV-VELECEF";
  variant: "Poll";
}
export interface NavVelned {
  name: "NAV-VELNED";
  iTOW: number;
  velN: number;
  velE: number;
  velD: number;
  speed: number;
  gSpeed: number;
  heading: number;
  sAcc: number;
  cAcc: number;
}
export interface NavVelnedPoll {
  name: "NAV-VELNED";
  variant: "Poll";
}
export interface NavHpposecef {
  name: "NAV-HPPOSECEF";
  version: number;
  reserved1: number;
  iTOW: number;
  ecefX: number;
  ecefY: number;
  ecefZ: number;
  ecefXHp: number;
  ecefYHp: number;
  ecefZHp: number;
  flags: number;
  pAcc: number;
}
export interface NavHpposecefPoll {
  name: "NAV-HPPOSECEF";
  variant: "Poll";
}
export interface NavHpposllh {
  name: "NAV-HPPOSLLH";
  version: number;
  reserved1: number;
  flags: number;
  iTOW: number;
  lon: number;
  lat: number;
  height: number;
  hMSL: number;
  lonHp: number;
  latHp: number;
  heigthHp: number;
  hMSLHp: number;
  hAcc: number;
  vAcc: number;
}
export interface NavHpposllhPoll {
  name: "NAV-HPPOSLLH";
  variant: "Poll";
}
export interface NavTimegps {
  name: "NAV-TIMEGPS";
  iTOW: number;
  fTOW: number;
  weeks: number;
  leapS: number;
  valid: number;
  tAcc: number;
}
export interface NavTimegpsPoll {
  name: "NAV-TIMEGPS";
  variant: "Poll";
}
export interface NavTimeutc {
  name: "NAV-TIMEUTC";
  iTOW: number;
  tAcc: number;
  nano: number;
  year: number;
  month: number;
  day: number;
  hour: number;
  min: number;
  sec: number;
  valid: {
    validTOW: boolean;
    validWKN: boolean;
    validUTC: boolean;
    utcStandard: number;
  };
}
export interface NavTimeutcPoll {
  name: "NAV-TIMEUTC";
  variant: "Poll";
}
export interface NavClock {
  name: "NAV-CLOCK";
  iTOW: number;
  clkB: number;
  clkD: number;
  tAcc: number;
  fAcc: number;
}
export interface NavClockPoll {
  name: "NAV-CLOCK";
  variant: "Poll";
}
export interface NavTimeglo {
  name: "NAV-TIMEGLO";
  iTOW: number;
  TOD: number;
  fTOD: number;
  Nt: number;
  N4: number;
  valid: number;
  tAcc: number;
}
export interface NavTimegloPoll {
  name: "NAV-TIMEGLO";
  variant: "Poll";
}
export interface NavTimebds {
  name: "NAV-TIMEBDS";
  iTOW: number;
  SOW: number;
  fSOW: number;
  week: number;
  leapS: number;
  valid: number;
  tAcc: number;
}
export interface NavTimebdsPoll {
  name: "NAV-TIMEBDS";
  variant: "Poll";
}
export interface NavTimegal {
  name: "NAV-TIMEGAL";
  iTOW: number;
  galTow: number;
  fGalTow: number;
  galWno: number;
  leapS: number;
  valid: number;
  tAcc: number;
}
export interface NavTimegalPoll {
  name: "NAV-TIMEGAL";
  variant: "Poll";
}
export interface NavTimels {
  name: "NAV-TIMELS";
  iTOW: number;
  version: number;
  reserved1: number;
  srcOfCurrLs: number;
  currLs: number;
  srcOfLsChange: number;
  lsChange: number;
  timeToLsEvent: number;
  dateOfLsGpsWn: number;
  dateOfLsGpsDn: number;
  reserved2: number;
  valid: number;
}
export interface NavTimelsPoll {
  name: "NAV-TIMELS";
  variant: "Poll";
}
export interface NavSvinfo {
  name: "NAV-SVINFO";
  iTOW: number;
  numCh: number;
  globalFlags: {
    chipGen: number;
    reserved: number;
  };
  reserved1: number;
  list: Array<{
    chn: number;
    svid: number;
    flags: number;
    quality: number;
    cno: number;
    elev: number;
    azim: number;
    prRes: number;
  }>;
}
export interface NavSvinfoPoll {
  name: "NAV-SVINFO";
  variant: "Poll";
}
export interface NavDgps {
  name: "NAV-DGPS";
  iTOW: number;
  age: number;
  baseId: number;
  baseHealth: number;
  numCh: number;
  status: number;
  reserved1: number;
  list: Array<{
    svid: number;
    flags: {
      channel: number;
      dgpsUsed: boolean;
    };
    ageC: number;
    prc: number;
    prrc: number;
  }>;
}
export interface NavDgpsPoll {
  name: "NAV-DGPS";
  variant: "Poll";
}
export interface NavSbas {
  name: "NAV-SBAS";
  iTOW: number;
  geo: number;
  mode: number;
  sys: number;
  service: number;
  cnt: number;
  reserved1: number;
  list: Array<{
    svid: number;
    flags: number;
    udre: number;
    svSys: number;
    svService: number;
    reserved2: number;
    prc: number;
    reserved3: number;
    ic: number;
  }>;
}
export interface NavSbasPoll {
  name: "NAV-SBAS";
  variant: "Poll";
}
export interface NavOrb {
  name: "NAV-ORB";
  iTOW: number;
  version: number;
  numSv: number;
  reserved1: number;
  list: Array<{
    gnssId: number;
    svid: number;
    svFlag: {
      health: number;
      visibility: number;
      reserved: number;
    };
    eph: {
      ephUsability: number;
      ephSource: number;
    };
    alm: {
      almUsability: number;
      almSource: number;
    };
    otherOrb: {
      anoAopUsability: number;
      type: number;
    };
  }>;
}
export interface NavOrbPoll {
  name: "NAV-ORB";
  variant: "Poll";
}
export interface NavSat {
  name: "NAV-SAT";
  iTOW: number;
  version: number;
  numSvs: number;
  reserved1: number;
  list: Array<{
    gnssId: number;
    svid: number;
    cno: number;
    elev: number;
    azim: number;
    prRes: number;
    flags: {
      qualityInd: number;
      svUsed: boolean;
      health: number;
      diffCorr: boolean;
      smoothed: boolean;
      orbitSource: number;
      ephAvail: boolean;
      almAvail: boolean;
      anoAvail: boolean;
      aopAvail: boolean;
      sbasCorrUsed: boolean;
      rtcmCorrUsed: boolean;
      prCorrUsed: boolean;
      crCorrUsed: boolean;
      doCorrUsed: boolean;
    };
  }>;
}
export interface NavSatPoll {
  name: "NAV-SAT";
  variant: "Poll";
}
export interface NavGeofence {
  name: "NAV-GEOFENCE";
  iTOW: number;
  version: number;
  status: number;
  numFences: number;
  combState: number;
  list: Array<{
    state: number;
    id: number;
  }>;
}
export interface NavGeofencePoll {
  name: "NAV-GEOFENCE";
  variant: "Poll";
}
export interface NavSvin {
  name: "NAV-SVIN";
  version: number;
  reserved1: number;
  iTOW: number;
  dur: number;
  meanX: number;
  meanY: number;
  meanZ: number;
  meanXHP: number;
  meanYHP: number;
  meanZHP: number;
  reserved2: number;
  meanAcc: number;
  obs: number;
  valid: number;
  active: number;
  reserved3: number;
}
export interface NavSvinPoll {
  name: "NAV-SVIN";
  variant: "Poll";
}
export interface NavRelposnedV1 {
  name: "NAV-RELPOSNED";
  variant: "V1";
  version: number;
  reserved1: number;
  refStationId: number;
  iTOW: number;
  relPosN: number;
  relPosE: number;
  relPosD: number;
  relPosLength: number;
  relPosHeading: number;
  reserved2: number;
  relPosHPN: number;
  relPosHPE: number;
  relPosHPD: number;
  relPosHPLength: number;
  accN: number;
  accE: number;
  accD: number;
  accLength: number;
  accHeading: number;
  reserved3: number;
  flags: {
    gnssFixOK: boolean;
    diffSoln: boolean;
    relPosValid: boolean;
    carrSoln: number;
    isMoving: boolean;
    refPosMiss: boolean;
    refObsMiss: boolean;
    relPosHeadingValid: boolean;
  };
}
export interface NavRelposned {
  name: "NAV-RELPOSNED";
  version: number;
  reserved1: number;
  refStationId: number;
  iTOW: number;
  relPosN: number;
  relPosE: number;
  relPosD: number;
  relPosHPN: number;
  relPosHPE: number;
  relPosHPD: number;
  reserved2: number;
  accN: number;
  accE: number;
  accD: number;
  flags: {
    gnssFixOK: boolean;
    diffSoln: boolean;
    relPosValid: boolean;
    carrSoln: number;
    isMoving: boolean;
    refPosMiss: boolean;
    refObsMiss: boolean;
  };
}
export interface NavRelposnedPoll {
  name: "NAV-RELPOSNED";
  variant: "Poll";
}
export interface NavSlas {
  name: "NAV-SLAS";
  iTOW: number;
  version: number;
  reserved0: number;
  gmsLon: number;
  gmsLat: number;
  gmsCode: number;
  qzssSvId: number;
  serviceFlags: number;
  cnt: number;
  list: Array<{
    gnssId: number;
    svid: number;
    sigId: number;
    reserved1: number;
    prc: number;
  }>;
}
export interface NavSlasPoll {
  name: "NAV-SLAS";
  variant: "Poll";
}
export interface NavSig {
  name: "NAV-SIG";
  iTOW: number;
  version: number;
  numSigs: number;
  reserved0: number;
  list: Array<{
    gnssId: number;
    svid: number;
    sigId: number;
    freqId: number;
    prRes: number;
    cno: number;
    qualityInd: number;
    corrSource: number;
    ionoModel: number;
    sigFlags: {
      health: number;
      bits: number;
    };
    reserved1: number;
  }>;
}
export interface NavSigPoll {
  name: "NAV-SIG";
  variant: "Poll";
}
export interface NavAopstatus {
  name: "NAV-AOPSTATUS";
  iTOW: number;
  aopCfg: number;
  status: number;
  reserved0: number;
  reserved1: number;
  availGPS: number;
  reserved2: number;
  reserved3: number;
}
export interface NavAopstatusUblox8 {
  name: "NAV-AOPSTATUS";
  variant: "ublox-8";
  iTOW: number;
  aopCfg: number;
  status: number;
  reserved1: number;
  reserved2: number;
  reserved3: number;
}
export interface NavAopstatusPoll {
  name: "NAV-AOPSTATUS";
  variant: "Poll";
}
export interface NavEoe {
  name: "NAV-EOE";
  iTOW: number;
}
export interface RxmRaw {
  name: "RXM-RAW";
  rcvTow: number;
  week: number;
  numSV: number;
  reserved1: number;
  list: Array<{
    cpMes: number;
    prMes: number;
    doMes: number;
    sv: number;
    mesQI: number;
    cno: number;
    lli: number;
  }>;
}
export interface RxmRawPoll {
  name: "RXM-RAW";
  variant: "Poll";
}
export interface RxmSfrb {
  name: "RXM-SFRB";
  cno: number;
  svid: number;
  dwrd: Array<number>;
}
export interface RxmSfrbx {
  name: "RXM-SFRBX";
  gnssId: number;
  svid: number;
  reserved1: number;
  freqId: number;
  numWords: number;
  chn: number;
  version: number;
  reserved3: number;
  dwrd: Array<number>;
}
export interface RxmMeasx {
  name: "RXM-MEASX";
  version: number;
  reserved1: number;
  gpsTOW: number;
  gloTOW: number;
  bdsTOW: number;
  reserved2: number;
  qzssTOW: number;
  gpsTOWacc: number;
  gloTOWacc: number;
  bdsTOWacc: number;
  reserved3: number;
  qzssTOWacc: number;
  numSV: number;
  flags: {
    towSet: number;
    reserved: number;
  };
  reserved4: number;
  list: Array<{
    gnssId: number;
    svid: number;
    cNo: number;
    mpathIndic: number;
    dopplerMS: number;
    dopplerHz: number;
    wholeChips: number;
    fracChips: number;
    codePhase: number;
    intCodePhase: number;
    pseuRangeRMSErr: number;
    reserved5: number;
  }>;
}
export interface RxmMeasxPoll {
  name: "RXM-MEASX";
  variant: "Poll";
}
export interface RxmRawx {
  name: "RXM-RAWX";
  rcvTow: number;
  week: number;
  leapS: number;
  numMeas: number;
  recStat: number;
  version: number;
  reserved1: number;
  list: Array<{
    prMes: number;
    cpMes: number;
    doMes: number;
    gnssId: number;
    svid: number;
    sigId: number;
    freqId: number;
    locktime: number;
    cno: number;
    prStdev: number;
    cpStdev: number;
    doStdev: number;
    trkStat: number;
    reserved3: number;
  }>;
}
export interface RxmRawxPoll {
  name: "RXM-RAWX";
  variant: "Poll";
}
export interface RxmSvsi {
  name: "RXM-SVSI";
  iTOW: number;
  week: number;
  numVis: number;
  numSV: number;
  list: Array<{
    svid: number;
    svFlag: {
      ura: number;
      healthy: boolean;
      ephVal: boolean;
      almVal: boolean;
      notAvail: boolean;
    };
    azim: number;
    elev: number;
    age: {
      almAge: number;
      ephAge: number;
    };
  }>;
}
export interface RxmSvsiPoll {
  name: "RXM-SVSI";
  variant: "Poll";
}
export interface RxmAlm {
  name: "RXM-ALM";
  svid: number;
  week: number;
  dwrd: Array<number> | null;
}
export interface RxmAlmPollSv {
  name: "RXM-ALM";
  variant: "Poll SV";
  svid: number;
}
export interface RxmAlmPoll {
  name: "RXM-ALM";
  variant: "Poll";
}
export interface RxmEph {
  name: "RXM-EPH";
  svid: number;
  how: number;
}
export interface RxmEphPollSv {
  name: "RXM-EPH";
  variant: "Poll SV";
  svid: number;
}
export interface RxmEphPoll {
  name: "RXM-EPH";
  variant: "Poll";
}
export interface RxmRtcm {
  name: "RXM-RTCM";
  version: number;
  flags: {
    crcFailed: boolean;
    msgUsed: number;
    bitsHigh: number;
  };
  subType: number;
  refStation: number;
  msgType: number;
}
export interface RxmPmreqV0 {
  name: "RXM-PMREQ";
  variant: "v0";
  version: number;
  reserved1: number;
  duration: number;
  flags: number;
  wakeupSources: number;
}
export interface RxmPmreq {
  name: "RXM-PMREQ";
  duration: number;
  flags: number;
}
export interface RxmRlmLong {
  name: "RXM-RLM";
  variant: "Long";
  version: number;
  type: number;
  svid: number;
  reserved1: number;
  beacon: Buffer;
  message: number;
  params: Buffer;
  reserved2: number;
}
export interface RxmRlmShort {
  name: "RXM-RLM";
  variant: "Short";
  version: number;
  type: number;
  svid: number;
  reserved1: number;
  beacon: Buffer;
  message: number;
  params: Buffer;
  reserved2: number;
}
export interface RxmImes {
  name: "RXM-IMES";
  numTx: number;
  version: number;
  reserved1: number;
  list: Array<{
    reserved2: number;
    txId: number;
    reserved3: number;
    cno: number;
    reserved4: number;
    doppler: number;
    position1_1: {
      pos1Floor: number;
      pos1Lat: number;
      reserved: number;
    };
    position1_2: {
      pos1Lon: number;
      flags: number;
    };
    position2_1: {
      pos2Floor: number;
      pos2Alt: number;
      pos2Acc: number;
      pos2Valid: boolean;
    };
    lat: number;
    lon: number;
    shortIdFrame: {
      shortId: number;
      shortValid: boolean;
      shortBoundary: boolean;
    };
    mediumIdLSB: number;
    mediumId_2: number;
  }>;
}
export interface RxmImesPoll {
  name: "RXM-IMES";
  variant: "Poll";
}
export interface InfError {
  name: "INF-ERROR";
  str: string;
}
export interface InfWarning {
  name: "INF-WARNING";
  str: string;
}
export interface InfNotice {
  name: "INF-NOTICE";
  str: string;
}
export interface InfTest {
  name: "INF-TEST";
  str: string;
}
export interface InfDebug {
  name: "INF-DEBUG";
  str: string;
}
export interface AckNak {
  name: "ACK-NAK";
  MsgId: number;
}
export interface AckAck {
  name: "ACK-ACK";
  MsgId: number;
}
export interface CfgPrtDdc {
  name: "CFG-PRT";
  variant: "DDC";
  portId: number;
  reserved1: number;
  txReady: {
    en: boolean;
    pol: boolean;
    pin: number;
    thres: number;
  };
  mode: {
    reservedLow: number;
    slaveAddr: number;
    reservedHigh: number;
  };
  reserved2: number;
  inProtoMask: number;
  outProtoMask: number;
  cfgPrtFlags: number;
  reserved3: number;
}
export interface CfgPrtUart {
  name: "CFG-PRT";
  variant: "UART";
  portId: number;
  reserved1: number;
  txReady: {
    en: boolean;
    pol: boolean;
    pin: number;
    thres: number;
  };
  mode: {
    reservedLow: number;
    charLen: number;
    reservedMid: number;
    parity: number;
    nStopBits: number;
    reservedHigh: number;
  };
  baudRate: number;
  inProtoMask: number;
  outProtoMask: number;
  cfgPrtFlags: number;
  reserved2: number;
}
export interface CfgPrtUsb {
  name: "CFG-PRT";
  variant: "USB";
  portId: number;
  reserved1: number;
  txReady: {
    en: boolean;
    pol: boolean;
    pin: number;
    thres: number;
  };
  reserved2: number;
  inProtoMask: number;
  outProtoMask: number;
  cfgPrtFlags: number;
  reserved3: number;
  reserved4: number;
}
export interface CfgPrtSpi {
  name: "CFG-PRT";
  variant: "SPI";
  portId: number;
  reserved1: number;
  txReady: {
    en: boolean;
    pol: boolean;
    pin: number;
    thres: number;
  };
  mode: {
    reservedLow: number;
    spiMode: number;
    flowControl: boolean;
    ffCnt: number;
    reservedHigh: number;
  };
  reserved2: number;
  inProtoMask: number;
  outProtoMask: number;
  cfgPrtFlags: number;
  reserved3: number;
}
export interface CfgPrtPortPoll {
  name: "CFG-PRT";
  variant: "Port Poll";
  portId: number;
}
export interface CfgPrtPoll {
  name: "CFG-PRT";
  variant: "Poll";
}
export interface CfgMsg {
  name: "CFG-MSG";
  MsgId: number;
  rates: Array<number>;
}
export interface CfgMsgCurrent {
  name: "CFG-MSG";
  variant: "Current";
  MsgId: number;
  rate: number;
}
export interface CfgMsgPoll {
  name: "CFG-MSG";
  variant: "Poll";
  MsgId: number;
}
export interface CfgInf {
  name: "CFG-INF";
  protocolId: number;
  reserved1: number;
  infMsgMask: Array<number>;
}
export interface CfgInfPoll {
  name: "CFG-INF";
  variant: "Poll";
}
export interface CfgRst {
  name: "CFG-RST";
  navBbrMask: number;
  resetMode: number;
  reserved1: number;
}
export interface CfgDat {
  name: "CFG-DAT";
  datumNum: number;
  datumName: string;
  majA: number;
  flat: number;
  dX: number;
  dY: number;
  dZ: number;
  rotX: number;
  rotY: number;
  rotZ: number;
  scale: number;
}
export interface CfgDatUser {
  name: "CFG-DAT";
  variant: "User";
  majA: number;
  flat: number;
  dX: number;
  dY: number;
  dZ: number;
  rotX: number;
  rotY: number;
  rotZ: number;
  scale: number;
}
export interface CfgDatStandard {
  name: "CFG-DAT";
  variant: "Standard";
  datumNum: number;
}
export interface CfgDatPoll {
  name: "CFG-DAT";
  variant: "Poll";
}
export interface CfgTp {
  name: "CFG-TP";
  interval: number;
  length: number;
  status: number;
  timeRef: number;
  flags: number;
  res: number;
  antennaCableDelay: number;
  rfGroupDelay: number;
  userDelay: number;
}
export interface CfgTpPoll {
  name: "CFG-TP";
  variant: "Poll";
}
export interface CfgRate {
  name: "CFG-RATE";
  measRate: number;
  navRate: number;
  timeRef: number;
}
export interface CfgRatePoll {
  name: "CFG-RATE";
  variant: "Poll";
}
export interface CfgCfg {
  name: "CFG-CFG";
  clearMask: number;
  saveMask: number;
  loadMask: number;
  deviceMask: number | null;
}
export interface CfgFxn {
  name: "CFG-FXN";
  flags: number;
  tReacq: number;
  tAcq: number;
  tReacqOff: number;
  tAcqOff: number;
  tOn: number;
  tOff: number;
  res: number;
  baseTow: number;
}
export interface CfgFxnPoll {
  name: "CFG-FXN";
  variant: "Poll";
}
export interface CfgRxm {
  name: "CFG-RXM";
  reserved1: number;
  lpMode: number;
}
export interface CfgRxmPoll {
  name: "CFG-RXM";
  variant: "Poll";
}
export interface CfgEkf {
  name: "CFG-EKF";
  disableEkf: number;
  actionFlags: number;
  configFlags: number;
  inverseFlags: number;
  reserved2: number;
  nomPPDist: number;
  nomZero: number;
  nomSens: number;
  rmsTemp: number;
  tempUpdate: number;
}
export interface CfgEkfPoll {
  name: "CFG-EKF";
  variant: "Poll";
}
export interface CfgAnt {
  name: "CFG-ANT";
  flags: number;
  pins: {
    pinSwitch: number;
    pinSCD: number;
    pinOCD: number;
    reconfig: boolean;
  };
}
export interface CfgAntPoll {
  name: "CFG-ANT";
  variant: "Poll";
}
export interface CfgSbas {
  name: "CFG-SBAS";
  mode: number;
  usage: number;
  maxSBAS: number;
  scanmode2: number;
  scanmode1: number;
}
export interface CfgSbasPoll {
  name: "CFG-SBAS";
  variant: "Poll";
}
export interface CfgNmeaV1 {
  name: "CFG-NMEA";
  variant: "V1";
  filter: number;
  nmeaVersion: number;
  numSV: number;
  flags: number;
  gnssToFilter: number;
  svNumbering: number;
  mainTalkerId: number;
  gsvTalkerId: number;
  version: number;
  bdsTalkerId: Buffer;
  reserved1: number;
}
export interface CfgNmeaV0 {
  name: "CFG-NMEA";
  variant: "V0";
  filter: number;
  nmeaVersion: number;
  numSV: number;
  flags: number;
  gnssToFilter: number;
  svNumbering: number;
  mainTalkerId: number;
  gsvTalkerId: number;
  version: number;
}
export interface CfgNmea {
  name: "CFG-NMEA";
  filter: number;
  nmeaVersion: number;
  numSV: number;
  flags: number;
}
export interface CfgNmeaPoll {
  name: "CFG-NMEA";
  variant: "Poll";
}
export interface CfgUsb {
  name: "CFG-USB";
  vendorId: number;
  productId: number;
  reserved1: number;
  reserved2: number;
  powerConsumption: number;
  flags: number;
  vendorString: string;
  productString: string;
  serialNumber: string;
}
export interface CfgUsbPoll {
  name: "CFG-USB";
  variant: "Poll";
}
export interface CfgTmode {
  name: "CFG-TMODE";
  timeMode: number;
  fixedPosX: number;
  fixedPosY: number;
  fixedPosZ: number;
  fixedPosVar: number;
  svinMinDur: number;
  svinVarLimit: number;
}
export interface CfgTmodePoll {
  name: "CFG-TMODE";
  variant: "Poll";
}
export interface CfgOdo {
  name: "CFG-ODO";
  version: number;
  reserved1: number;
  flags: number;
  odoCfg: {
    profile: number;
    reserved: number;
  };
  reserved2: number;
  cogMaxSpeed: number;
  cogMaxPosAcc: number;
  reserved3: number;
  velLpGain: number;
  cogLpGain: number;
  reserved4: number;
}
export interface CfgOdoPoll {
  name: "CFG-ODO";
  variant: "Poll";
}
export interface CfgNvs {
  name: "CFG-NVS";
  clearMask: number;
  saveMask: number;
  loadMask: number;
  deviceMask: number;
}
export interface CfgNavx5 {
  name: "CFG-NAVX5";
  version: number;
  mask1: number;
  mask2: number;
  reserved1: number;
  minSVs: number;
  maxSVs: number;
  minCNO: number;
  reserved2: number;
  iniFix3D: number;
  reserved3: number;
  ackAiding: number;
  wknRollover: number;
  sigAttenCompMode: number;
  reserved4: number;
  reserved5: number;
  reserved6: number;
  usePPP: number;
  aopCfg: number;
  reserved7: number;
  aopOrbMaxErr: number;
  reserved8: number;
  reserved9: number;
  useAdr: number;
  reserved10: number;
  reserved11: number;
}
export interface CfgNavx5 {
  name: "CFG-NAVX5";
  version: number;
  mask1: number;
  mask2: number;
  reserved1: number;
  minSVs: number;
  maxSVs: number;
  minCNO: number;
  reserved2: number;
  iniFix3D: number;
  reserved3: number;
  ackAiding: number;
  wknRollover: number;
  sigAttenCompMode: number;
  reserved4: number;
  reserved5: number;
  reserved6: number;
  usePPP: number;
  aopCfg: number;
  reserved7: number;
  aopOrbMaxErr: number;
  reserved8: number;
  reserved9: number;
  useAdr: number;
}
export interface CfgNavx5 {
  name: "CFG-NAVX5";
  version: number;
  mask1: number;
  mask2: number;
  reserved1: number;
  minSVs: number;
  maxSVs: number;
  minCNO: number;
  reserved2: number;
  iniFix3D: number;
  reserved3: number;
  ackAiding: number;
  wknRollover: number;
  reserved4: number;
  usePPP: number;
  aopCfg: number;
  reserved5: number;
  aopOrbMaxErr: number;
  reserved6: number;
  reserved7: number;
  useAdr: number;
}
export interface CfgNavx5Poll {
  name: "CFG-NAVX5";
  variant: "Poll";
}
export interface CfgNav5 {
  name: "CFG-NAV5";
  mask: number;
  dynModel: number;
  fixMode: number;
  fixedAlt: number;
  fixedAltVar: number;
  minElev: number;
  drLimit: number;
  pDop: number;
  tDop: number;
  pAcc: number;
  tAcc: number;
  staticHoldThresh: number;
  dgnssTimeout: number;
  cnoThreshNumSVs: number;
  cnoThresh: number;
  reserved1: number;
  staticHoldMaxDist: number;
  utcStandard: number;
  reserved2: number;
}
export interface CfgNav5Poll {
  name: "CFG-NAV5";
  variant: "Poll";
}
export interface CfgTp5 {
  name: "CFG-TP5";
  tpIdx: number;
  version: number;
  reserved1: number;
  antCableDelay: number;
  rfGroupDelay: number;
  freq: number | null;
  period: number | null;
  freqLock: number | null;
  periodLock: number | null;
  pulseLen: number | null;
  ratio: number | null;
  pulseLenLock: number | null;
  ratioLock: number | null;
  userConfigDelay: number;
  flags: {
    bits: number;
    gridUtcGnss: number;
    syncMode: number;
    reserved: number;
  };
}
export interface CfgTp5PollSelect {
  name: "CFG-TP5";
  variant: "Poll Select";
  tpIdx: number;
}
export interface CfgTp5Poll {
  name: "CFG-TP5";
  variant: "Poll";
}
export interface CfgPm {
  name: "CFG-PM";
  version: number;
  res1: number;
  res2: number;
  res3: number;
  flags: {
    res1: number;
    internal: number;
    bitsMid: number;
    limitPeakCurr: number;
    bitsHigh: number;
  };
  updatePeriod: number;
  searchPeriod: number;
  gridOffset: number;
  onTime: number;
  minAcqTime: number;
}
export interface CfgPmPoll {
  name: "CFG-PM";
  variant: "Poll";
}
export interface CfgRinv {
  name: "CFG-RINV";
  flags: number;
  data: Buffer;
}
export interface CfgRinvPoll {
  name: "CFG-RINV";
  variant: "Poll";
}
export interface CfgItfm {
  name: "CFG-ITFM";
  config: {
    bbThreshold: number;
    cwThreshold: number;
    algorithmBits: number;
    bits: number;
  };
  config2: {
    generalBits: number;
    antSetting: number;
    bitsHigh: number;
  };
}
export interface CfgItfmPoll {
  name: "CFG-ITFM";
  variant: "Poll";
}
export interface CfgPm2V2 {
  name: "CFG-PM2";
  variant: "V2";
  version: number;
  reserved1: number;
  maxStartupStateDur: number;
  reserved2: number;
  flags: {
    extintSel: boolean;
    extintWake: boolean;
    extintBackup: boolean;
    extintInactive: boolean;
    limitPeakCurr: number;
    waitTimeFix: boolean;
    updateRTC: boolean;
    updateEPH: boolean;
    doNotEnterOff: boolean;
    mode: number;
    reserved: number;
  };
  updatePeriod: number;
  searchPeriod: number;
  gridOffset: number;
  onTime: number;
  minAcqTime: number;
  reserved3: Array<number>;
  extintInactivityMs: number;
}
export interface CfgPm2 {
  name: "CFG-PM2";
  version: number;
  reserved1: number;
  maxStartupStateDur: number;
  reserved2: number;
  flags: {
    extintSel: boolean;
    extintWake: boolean;
    extintBackup: boolean;
    extintInactive: boolean;
    limitPeakCurr: number;
    waitTimeFix: boolean;
    updateRTC: boolean;
    updateEPH: boolean;
    doNotEnterOff: boolean;
    mode: number;
    reserved: number;
  };
  updatePeriod: number;
  searchPeriod: number;
  gridOffset: number;
  onTime: number;
  minAcqTime: number;
  reserved3: Array<number>;
}
export interface CfgPm2Poll {
  name: "CFG-PM2";
  variant: "Poll";
}
export interface CfgTmode2 {
  name: "CFG-TMODE2";
  timeMode: number;
  reserved1: number;
  flags: number;
  ecefX: number | null;
  lat: number | null;
  ecefY: number | null;
  lon: number | null;
  ecefZ: number | null;
  alt: number | null;
  fixedPosAcc: number;
  svinMinDur: number;
  svinVarLimit: number;
}
export interface CfgTmode2Poll {
  name: "CFG-TMODE2";
  variant: "Poll";
}
export interface CfgGnss {
  name: "CFG-GNSS";
  msgVer: number;
  numTrkChHw: number;
  numTrkChUse: number;
  numConfigBlocks: number;
  list: Array<{
    gnssId: number;
    resTrkCh: number;
    maxTrkCh: number;
    reserved1: number;
    flags: {
      enable: boolean;
      sigCfgMask: number;
      reserved: number;
    };
  }>;
}
export interface CfgGnssPoll {
  name: "CFG-GNSS";
  variant: "Poll";
}
export interface CfgLogfilter {
  name: "CFG-LOGFILTER";
  version: number;
  flags: number;
  minInterval: number;
  timeThreshold: number;
  speedThreshold: number;
  positionThres: number;
}
export interface CfgLogfilterPoll {
  name: "CFG-LOGFILTER";
  variant: "Poll";
}
export interface CfgTxslot {
  name: "CFG-TXSLOT";
  version: number;
  enable: number;
  refTp: number;
  reserved1: number;
  end: Array<number>;
}
export interface CfgPwr {
  name: "CFG-PWR";
  version: number;
  reserved1: number;
  state: number;
}
export interface CfgHnr {
  name: "CFG-HNR";
  highNavRate: number;
  reserved1: number;
}
export interface CfgHnrPoll {
  name: "CFG-HNR";
  variant: "Poll";
}
export interface CfgEsrc {
  name: "CFG-ESRC";
  version: number;
  numSources: number;
  reserved1: number;
  list: Array<{
    extInt: number;
    sourceType: number;
    flags: number;
    freq: number;
    reserved2: number;
    withTemp: number;
    withAge: number;
    timeToTemp: number;
    maxDevLifeTime: number;
    offset: number;
    offsetUncertainty: number;
    jitter: number;
  }>;
}
export interface CfgEsrcPoll {
  name: "CFG-ESRC";
  variant: "Poll";
}
export interface CfgDosc {
  name: "CFG-DOSC";
  version: number;
  numOsc: number;
  reserved1: number;
  list: Array<{
    oscId: number;
    reserved2: number;
    flags: {
      isCalibrated: boolean;
      controlIf: number;
      reserved: number;
    };
    freq: number;
    phaseOffset: number;
    withTemp: number;
    withAge: number;
    timeToTemp: number;
    reserved3: number;
    gainVco: number;
    gainUncertainty: number;
    reserved4: number;
  }>;
}
export interface CfgDoscPoll {
  name: "CFG-DOSC";
  variant: "Poll";
}
export interface CfgSmgr {
  name: "CFG-SMGR";
  version: number;
  minGNSSFix: number;
  maxFreqChangeRate: number;
  maxPhaseCorrRate: number;
  reserved1: number;
  freqTolerance: number;
  timeTolerance: number;
  messageCfg: number;
  maxSlewRate: number;
  flags: {
    disableInternal: boolean;
    disableExternal: boolean;
    preferenceMode: boolean;
    enableGNSS: boolean;
    enableEXTINT0: boolean;
    enableEXTINT1: boolean;
    enableHostMeasInt: boolean;
    enableHostMeasExt: boolean;
    useAnyFix: boolean;
    disableMaxSlewRate: boolean;
    issueFreqWarning: boolean;
    issueTimeWarning: boolean;
    TPCoherent: number;
    disableOffset: boolean;
  };
}
export interface CfgSmgrPoll {
  name: "CFG-SMGR";
  variant: "Poll";
}
export interface CfgGeofence {
  name: "CFG-GEOFENCE";
  version: number;
  numFences: number;
  confLvl: number;
  reserved1: number;
  pioEnabled: number;
  pinPolarity: number;
  pin: number;
  reserved2: number;
  list: Array<{
    lat: number;
    lon: number;
    radius: number;
  }>;
}
export interface CfgGeofencePoll {
  name: "CFG-GEOFENCE";
  variant: "Poll";
}
export interface CfgDgnss {
  name: "CFG-DGNSS";
  dgnssMode: number;
  reserved1: number;
}
export interface CfgDgnssPoll {
  name: "CFG-DGNSS";
  variant: "Poll";
}
export interface CfgTmode3 {
  name: "CFG-TMODE3";
  version: number;
  reserved1: number;
  flags: {
    mode: number;
    lla: boolean;
  };
  ecef: {
    ecefX: number;
    ecefY: number;
    ecefZ: number;
    ecefXHP: number;
    ecefYHP: number;
    ecefZHP: number;
  } | null;
  lla: {
    lat: number;
    lon: number;
    alt: number;
    latHP: number;
    lonHP: number;
    altHP: number;
  } | null;
  reserved2: number;
  fixedPosAcc: number;
  svinMinDur: number;
  svinVarLimit: number;
  reserved3: number;
}
export interface CfgTmode3Poll {
  name: "CFG-TMODE3";
  variant: "Poll";
}
export interface CfgFixseed {
  name: "CFG-FIXSEED";
  version: number;
  length: number;
  reserved1: number;
  seedHi: number;
  seedLo: number;
  list: Array<number>;
}
export interface CfgPms {
  name: "CFG-PMS";
  version: number;
  powerSetupValue: number;
  period: number;
  onTime: number;
  reserved1: number;
}
export interface CfgPmsPoll {
  name: "CFG-PMS";
  variant: "Poll";
}
export interface CfgValset {
  name: "CFG-VALSET";
  version: number;
  layers: number;
  reserved0: number;
  cfgdata: Array<{
    Key: number;
    Val: null;
  }>;
}
export interface CfgValget {
  name: "CFG-VALGET";
  version: number;
  layer: number;
  position: number;
  cfgdata: Array<{
    Key: number;
    Val: null;
  }>;
}
export interface CfgValgetPoll {
  name: "CFG-VALGET";
  variant: "Poll";
  version: number;
  layer: number;
  position: number;
  keys: Array<number>;
}
export interface CfgValdel {
  name: "CFG-VALDEL";
  version: number;
  layers: number;
  transaction: {
    action: number;
    reserved: number;
  };
  reserved0: number;
  keys: Array<number>;
}
export interface UpdSosRestored {
  name: "UPD-SOS";
  variant: "Restored";
  cmd: number;
  reserved1: number;
  response: number;
  reserved2: number;
}
export interface UpdSosAck {
  name: "UPD-SOS";
  variant: "Ack";
  cmd: number;
  reserved1: number;
  response: number;
  reserved2: number;
}
export interface UpdSosClear {
  name: "UPD-SOS";
  variant: "Clear";
  cmd: number;
  reserved1: number;
}
export interface UpdSosCreate {
  name: "UPD-SOS";
  variant: "Create";
  cmd: number;
  reserved1: number;
}
export interface UpdSosPoll {
  name: "UPD-SOS";
  variant: "Poll";
}
export interface MonIo {
  name: "MON-IO";
  list: Array<{
    rxBytes: number;
    txBytes: number;
    parityErrs: number;
    framingErrs: number;
    overrunErrs: number;
    breakCond: number;
    rxBusy: number;
    txBusy: number;
    reserved1: number;
  }>;
}
export interface MonIoPoll {
  name: "MON-IO";
  variant: "Poll";
}
export interface MonVer {
  name: "MON-VER";
  swVersion: string;
  hwVersion: string;
  list: Array<string>;
}
export interface MonVerPoll {
  name: "MON-VER";
  variant: "Poll";
}
export interface MonMsgpp {
  name: "MON-MSGPP";
  msg1: Array<number>;
  msg2: Array<number>;
  msg3: Array<number>;
  msg4: Array<number>;
  msg5: Array<number>;
  msg6: Array<number>;
  skipped: Array<number>;
}
export interface MonMsgppPoll {
  name: "MON-MSGPP";
  variant: "Poll";
}
export interface MonRxbuf {
  name: "MON-RXBUF";
  pending: Array<number>;
  usage: Array<number>;
  peakUsage: Array<number>;
}
export interface MonRxbufPoll {
  name: "MON-RXBUF";
  variant: "Poll";
}
export interface MonTxbuf {
  name: "MON-TXBUF";
  pending: Array<number>;
  usage: Array<number>;
  peakUsage: Array<number>;
  tUsage: number;
  tPeakusage: number;
  errors: {
    limit: number;
    mem: boolean;
    alloc: boolean;
  };
  reserved1: number;
}
export interface MonTxbufPoll {
  name: "MON-TXBUF";
  variant: "Poll";
}
export interface MonHw {
  name: "MON-HW";
  pinSel: number;
  pinBank: number;
  pinDir: number;
  pinVal: number;
  noisePerMS: number;
  agcCnt: number;
  aStatus: number;
  aPower: number;
  flags: {
    rtcCalib: boolean;
    safeBoot: boolean;
    jammingState: number;
    xtalAbsent: boolean;
  };
  reserved1: number;
  usedMask: number;
  VP: Buffer;
  jamInd: number;
  reserved2: number;
  pinIrq: number;
  pullH: number;
  pullL: number;
}
export interface MonHwPoll {
  name: "MON-HW";
  variant: "Poll";
}
export interface MonHw2 {
  name: "MON-HW2";
  ofsI: number;
  magI: number;
  ofsQ: number;
  magQ: number;
  cfgSource: number;
  reserved1: number;
  lowLevCfg: number;
  reserved2: number;
  postStatus: number;
  reserved3: number;
}
export interface MonHw2Poll {
  name: "MON-HW2";
  variant: "Poll";
}
export interface MonRxr {
  name: "MON-RXR";
  flags: number;
}
export interface MonPatch {
  name: "MON-PATCH";
  version: number;
  nEntries: number;
  list: Array<{
    patchInfo: {
      activated: boolean;
      location: number;
      res4: number;
    };
    comparatorNumber: number;
    patchAddress: number;
    patchData: number;
  }>;
}
export interface MonPatchPoll {
  name: "MON-PATCH";
  variant: "Poll";
}
export interface MonGnss {
  name: "MON-GNSS";
  version: number;
  supported: number;
  defaultGnss: number;
  enabled: number;
  simultaneous: number;
  reserved1: number;
}
export interface MonGnssPoll {
  name: "MON-GNSS";
  variant: "Poll";
}
export interface MonSmgr {
  name: "MON-SMGR";
  version: number;
  reserved1: number;
  iTOW: number;
  intOsc: {
    intOscState: number;
    intOscCalib: boolean;
    intOscDisc: boolean;
  };
  extOsc: {
    extOscState: number;
    extOscCalib: boolean;
    extOscDisc: boolean;
  };
  discSrc: number;
  gnss: number;
  extInt0: number;
  extInt1: number;
}
export interface MonSmgrPoll {
  name: "MON-SMGR";
  variant: "Poll";
}
export interface MonSpan {
  name: "MON-SPAN";
  version: number;
  numRfblocks: number;
  reserved0: number;
  list: Array<{
    spectrum: Array<number>;
    span: number;
    res: number;
    center: number;
    pga: number;
    reserved1: number;
  }>;
}
export interface MonSpanPoll {
  name: "MON-SPAN";
  variant: "Poll";
}
export interface MonComms {
  name: "MON-COMMS";
  version: number;
  nPorts: number;
  txErrors: number;
  reserved0: number;
  protIds: Array<number>;
  list: Array<{
    portId: number;
    txPending: number;
    txBytes: number;
    txUsage: number;
    txPeakUsage: number;
    rxPending: number;
    rxBytes: number;
    rxUsage: number;
    rxPeakUsage: number;
    overrunErrs: number;
    msgs: Array<number>;
    reserved1: number;
    skipped: number;
  }>;
}
export interface MonPatchPoll {
  name: "MON-PATCH";
  variant: "Poll";
}
export interface MonHw3 {
  name: "MON-HW3";
  version: number;
  nPins: number;
  flags: number;
  hwVersion: string;
  reserved0: Buffer;
  list: Array<{
    pinId: number;
    pinMask: {
      bitsLow: number;
      pinBank: number;
      bitsHigh: number;
    };
    VP: number;
    reserved1: number;
  }>;
}
export interface MonHw3Poll {
  name: "MON-HW3";
  variant: "Poll";
}
export interface MonRf {
  name: "MON-RF";
  version: number;
  nBlocks: number;
  reserved0: number;
  list: Array<{
    blockId: number;
    flags: {
      jammingState: number;
      res1: number;
    };
    antStatus: number;
    antPower: number;
    postStatus: number;
    reserved1: number;
    noisePerMS: number;
    agcCnt: number;
    jamInd: number;
    ofsI: number;
    magI: number;
    ofsQ: number;
    magQ: number;
    reserved2: number;
  }>;
}
export interface MonRfPoll {
  name: "MON-RF";
  variant: "Poll";
}
export interface AidReq {
  name: "AID-REQ";
}
export interface AidIni {
  name: "AID-INI";
  ecefX: number | null;
  lat: number | null;
  ecefY: number | null;
  lon: number | null;
  ecefZ: number | null;
  alt: number | null;
  posAcc: number;
  tmCfg: number;
  wno: number | null;
  date: {
    year: number;
    month: number;
  } | null;
  tow: number | null;
  time: {
    day: number;
    hour: number;
    min: number;
    sec: number;
  } | null;
  towNs: number;
  tAccMs: number;
  tAccNs: number;
  clkD: number | null;
  freq: number | null;
  clkDAcc: number | null;
  freqAcc: number | null;
  flags: number;
}
export interface AidIniPoll {
  name: "AID-INI";
  variant: "Poll";
}
export interface AidHui {
  name: "AID-HUI";
  health: number;
  utcA0: number;
  utcA1: number;
  utcTOW: number;
  utcWNT: number;
  utcLS: number;
  utcWNF: number;
  utcDN: number;
  utcLSF: number;
  utcSpare: number;
  klobA0: number;
  klobA1: number;
  klobA2: number;
  klobA3: number;
  klobB0: number;
  klobB1: number;
  klobB2: number;
  klobB3: number;
  flags: number;
}
export interface AidHuiPoll {
  name: "AID-HUI";
  variant: "Poll";
}
export interface AidData {
  name: "AID-DATA";
}
export interface AidAlm {
  name: "AID-ALM";
  svid: number;
  week: number;
  dwrd: Array<number> | null;
}
export interface AidAlmPollSv {
  name: "AID-ALM";
  variant: "Poll SV";
  svid: number;
}
export interface AidAlmPoll {
  name: "AID-ALM";
  variant: "Poll";
}
export interface AidEph {
  name: "AID-EPH";
  svid: number;
  how: number;
}
export interface AidEphPollSv {
  name: "AID-EPH";
  variant: "Poll SV";
  svid: number;
}
export interface AidEphPoll {
  name: "AID-EPH";
  variant: "Poll";
}
export interface AidAlpsrv {
  name: "AID-ALPSRV";
  idSize: number;
  type: number;
  ofs: number;
  size: number;
  fileId: number;
  dataSize: number;
  id1: number;
  id2: number;
  id3: number;
  data: Buffer;
}
export interface AidAlpsrvToServer {
  name: "AID-ALPSRV";
  variant: "To Server";
  idSize: number;
  type: number;
  ofs: number;
  size: number;
  fileId: number;
  data: Array<number>;
}
export interface AidAopUblox8 {
  name: "AID-AOP";
  variant: "ublox-8";
  gnssId: number;
  svid: number;
  reserved1: number;
  data: Buffer;
}
export interface AidAop {
  name: "AID-AOP";
  svid: number;
  data: Buffer;
  optionals: {
    optional0: Buffer;
    optional1: Buffer;
    optional2: Buffer;
  } | null;
}
export interface AidAopPollSv {
  name: "AID-AOP";
  variant: "Poll SV";
  svid: number;
}
export interface AidAopPoll {
  name: "AID-AOP";
  variant: "Poll";
}
export interface AidAlp {
  name: "AID-ALP";
  predTow: number;
  predDur: number;
  age: number;
  predWno: number;
  almWno: number;
  reserved1: number;
  svs: number;
  reserved2: number;
  reserved3: number;
}
export interface AidAlpStatus {
  name: "AID-ALP";
  variant: "Status";
  status: number;
}
export interface AidAlpData {
  name: "AID-ALP";
  variant: "Data";
  alpData: Array<number>;
}
export interface TimTp {
  name: "TIM-TP";
  towMS: number;
  towSubMS: number;
  qErr: number;
  week: number;
  flags: {
    timeBase: boolean;
    utc: boolean;
    raim: number;
    qErrInvalid: boolean;
  };
  refInfo: {
    timeRefGnss: number;
    utcStandard: number;
  };
}
export interface TimTpPoll {
  name: "TIM-TP";
  variant: "Poll";
}
export interface TimTm2 {
  name: "TIM-TM2";
  ch: number;
  flags: {
    mode: boolean;
    run: boolean;
    newFallingEdge: boolean;
    timeBase: number;
    utc: boolean;
    time: boolean;
    newRisingEdge: boolean;
  };
  count: number;
  wnR: number;
  wnF: number;
  towMsR: number;
  towSubMsR: number;
  towMsF: number;
  towSubMsF: number;
  accEst: number;
}
export interface TimTm2Poll {
  name: "TIM-TM2";
  variant: "Poll";
}
export interface TimVrfy {
  name: "TIM-VRFY";
  iTOW: number;
  frac: number;
  deltaMs: number;
  deltaNs: number;
  wno: number;
  flags: {
    src: number;
    reserved: number;
  };
  reserved1: number;
}
export interface TimVrfyPoll {
  name: "TIM-VRFY";
  variant: "Poll";
}
export interface TimSvin {
  name: "TIM-SVIN";
  dur: number;
  meanX: number;
  meanY: number;
  meanZ: number;
  meanV: number;
  obs: number;
  valid: number;
  active: number;
  reserved1: number;
}
export interface TimSvinPoll {
  name: "TIM-SVIN";
  variant: "Poll";
}
export interface TimDosc {
  name: "TIM-DOSC";
  version: number;
  reserved1: number;
  value: number;
}
export interface TimTos {
  name: "TIM-TOS";
  version: number;
  gnssId: number;
  reserved1: number;
  flags: {
    leapNow: boolean;
    leapSoon: boolean;
    leapPositive: boolean;
    timeInLimit: boolean;
    intOscInLimit: boolean;
    extOscInLimit: boolean;
    gnssTimeValid: boolean;
    UTCTimeValid: boolean;
    DiscSrc: number;
    raim: boolean;
    cohPulse: boolean;
    lockedPulse: boolean;
  };
  year: number;
  month: number;
  day: number;
  hour: number;
  min: number;
  sec: number;
  utcStandard: number;
  utcOffset: number;
  utcUncertainty: number;
  week: number;
  TOW: number;
  gnssOffset: number;
  gnssUncertainy: number;
  intOscOffset: number;
  intOscUncertainty: number;
  extOscOffset: number;
  extOscUncertainty: number;
}
export interface TimSmeas {
  name: "TIM-SMEAS";
  version: number;
  numMeas: number;
  reserved1: number;
  iTOW: number;
  reserved2: number;
  list: Array<{
    sourceId: number;
    flags: number;
    phaseOffsetFrac: number;
    phaseUncFrac: number;
    phaseOffset: number;
    phaseUnc: number;
    reserved3: number;
    freqOffset: number;
    freqUnc: number;
  }>;
}
export interface TimVcocal {
  name: "TIM-VCOCAL";
  type: number;
  version: number;
  oscId: number;
  reserved1: number;
  gainUncertainty: number;
  gainVco: number;
}
export interface TimVcocalExtended {
  name: "TIM-VCOCAL";
  variant: "Extended";
  type: number;
  version: number;
  oscId: number;
  srcId: number;
  reserved1: number;
  raw0: number;
  raw1: number;
  maxStepSize: number;
}
export interface TimVcocalStop {
  name: "TIM-VCOCAL";
  variant: "Stop";
  type: number;
}
export interface TimVcocalPoll {
  name: "TIM-VCOCAL";
  variant: "Poll";
}
export interface TimFchg {
  name: "TIM-FCHG";
  version: number;
  reserved1: number;
  iTOW: number;
  intDeltaFreq: number;
  intDeltaFreqUnc: number;
  intRaw: number;
  extDeltaFreq: number;
  extDeltaFreqUnc: number;
  extRaw: number;
}
export interface TimFchgPoll {
  name: "TIM-FCHG";
  variant: "Poll";
}
export interface EsfMeas {
  name: "ESF-MEAS";
  timeTag: number;
  flags: {
    timeMarkSent: number;
    timeMarkEdge: boolean;
    calibTtagValid: boolean;
  };
  id: number;
  list: Array<{
    dataField: number;
    dataType: number;
    reserved: number;
  }>;
  calibTtag: number | null;
}
export interface EsfMeasPoll {
  name: "ESF-MEAS";
  variant: "Poll";
}
export interface EsfRaw {
  name: "ESF-RAW";
  reserved1: number;
  data: Array<{
    dataField: number;
    dataType: number;
    sTtag: number;
  }>;
}
export interface EsfStatus {
  name: "ESF-STATUS";
  iTOW: number;
  version: number;
  reserved1: number;
  fusionMode: number;
  reserved2: number;
  numSens: number;
  list: Array<{
    sensStatus1: {
      type: number;
      used: boolean;
      ready: boolean;
    };
    sensStatus2: {
      calibStatus: number;
      timeStatus: number;
      reserved: number;
    };
    freq: number;
    faults: number;
  }>;
}
export interface EsfStatusPoll {
  name: "ESF-STATUS";
  variant: "Poll";
}
export interface EsfIns {
  name: "ESF-INS";
  bitfield0: {
    version: number;
    xAngRateValid: boolean;
    yAngRateValid: boolean;
    zAngRateValid: boolean;
    xAccelValid: boolean;
    yAccelValid: boolean;
    zAccelValid: boolean;
  };
  reserved1: number;
  iTOW: number;
  xAngRate: number;
  yAngRate: number;
  zAngRate: number;
  xAccel: number;
  yAccel: number;
  zAccel: number;
}
export interface EsfInsPoll {
  name: "ESF-INS";
  variant: "Poll";
}
export interface MgaGpsEph {
  name: "MGA-GPS-EPH";
  type: number;
  version: number;
  svid: number;
  reserved1: number;
  fitInterval: number;
  uraIndex: number;
  svHealth: number;
  tgd: number;
  iodc: number;
  toc: number;
  reserved2: number;
  af2: number;
  af1: number;
  af0: number;
  crs: number;
  deltaN: number;
  m0: number;
  cuc: number;
  cus: number;
  e: number;
  sqrtA: number;
  toe: number;
  cic: number;
  omega0: number;
  cis: number;
  crc: number;
  i0: number;
  omega: number;
  omegaDot: number;
  idot: number;
  reserved3: number;
}
export interface MgaGpsAlm {
  name: "MGA-GPS-ALM";
  type: number;
  version: number;
  svid: number;
  svHealth: number;
  e: number;
  almWNa: number;
  toa: number;
  deltaI: number;
  omegaDot: number;
  sqrtA: number;
  omega0: number;
  omega: number;
  m0: number;
  af0: number;
  af1: number;
  reserved1: number;
}
export interface MgaGpsHealth {
  name: "MGA-GPS-HEALTH";
  type: number;
  version: number;
  reserved1: number;
  healthCode: Buffer;
  reserved2: number;
}
export interface MgaGpsUtc {
  name: "MGA-GPS-UTC";
  type: number;
  version: number;
  reserved1: number;
  utcA0: number;
  utcA1: number;
  utcDtLS: number;
  utcTot: number;
  utcWNt: number;
  utcWNlsf: number;
  utcDn: number;
  utcDtLSF: number;
  reserved2: number;
}
export interface MgaGpsIono {
  name: "MGA-GPS-IONO";
  type: number;
  version: number;
  reserved1: number;
  ionoAlpha0: number;
  ionoAlpha1: number;
  ionoAlpha2: number;
  ionoAlpha3: number;
  ionoBeta0: number;
  ionoBeta1: number;
  ionoBeta2: number;
  ionoBeta3: number;
  reserved2: number;
}
export interface MgaGalEph {
  name: "MGA-GAL-EPH";
  type: number;
  version: number;
  svid: number;
  reserved1: number;
  iodNav: number;
  deltaN: number;
  m0: number;
  e: number;
  sqrtA: number;
  omega0: number;
  i0: number;
  omega: number;
  omegaDot: number;
  iDot: number;
  cuc: number;
  cus: number;
  crc: number;
  crs: number;
  cic: number;
  cis: number;
  toe: number;
  af0: number;
  af1: number;
  af2: number;
  sisaIndexE1E5b: number;
  toc: number;
  bgdE1E5b: number;
  reserved2: number;
  healthE1B: number;
  dataValidityE1B: number;
  healthE5b: number;
  dataValidityE5b: number;
  reserved3: number;
}
export interface MgaGalAlm {
  name: "MGA-GAL-ALM";
  type: number;
  version: number;
  svid: number;
  reserved1: number;
  ioda: number;
  almWNa: number;
  toa: number;
  deltaSqrtA: number;
  e: number;
  deltaI: number;
  omega0: number;
  omegaDot: number;
  omega: number;
  m0: number;
  af0: number;
  af1: number;
  healthE1B: number;
  healthE5b: number;
  reserved2: number;
}
export interface MgaGalTimeoffset {
  name: "MGA-GAL-TIMEOFFSET";
  type: number;
  version: number;
  reserved1: number;
  a0G: number;
  a1G: number;
  t0G: number;
  wn0G: number;
  reserved2: number;
}
export interface MgaGalUtc {
  name: "MGA-GAL-UTC";
  type: number;
  version: number;
  reserved1: number;
  a0: number;
  a1: number;
  dtLS: number;
  tot: number;
  wnt: number;
  wnLSF: number;
  dN: number;
  dTLSF: number;
  reserved2: number;
}
export interface MgaBdsEph {
  name: "MGA-BDS-EPH";
  type: number;
  version: number;
  svid: number;
  reserved1: number;
  SatH1: number;
  IODC: number;
  a2: number;
  a1: number;
  a0: number;
  toc: number;
  TGD1: number;
  URAI: number;
  IODE: number;
  toe: number;
  sqrtA: number;
  e: number;
  omega: number;
  Deltan: number;
  IDOT: number;
  M0: number;
  Omega0: number;
  OmegaDot: number;
  i0: number;
  Cuc: number;
  Cus: number;
  Crc: number;
  Crs: number;
  Cic: number;
  Cis: number;
  reserved2: number;
}
export interface MgaBdsAlm {
  name: "MGA-BDS-ALM";
  type: number;
  version: number;
  svid: number;
  reserved1: number;
  Wna: number;
  toa: number;
  deltaI: number;
  sqrtA: number;
  e: number;
  omega: number;
  M0: number;
  Omega0: number;
  omegaDot: number;
  a0: number;
  a1: number;
  reserved2: number;
}
export interface MgaBdsHealth {
  name: "MGA-BDS-HEALTH";
  type: number;
  version: number;
  reserved1: number;
  healthCode: Array<number>;
  reserved2: number;
}
export interface MgaBdsUtc {
  name: "MGA-BDS-UTC";
  type: number;
  version: number;
  reserved1: number;
  a0UTC: number;
  a1UTC: number;
  dtLS: number;
  reserved2: number;
  wnRec: number;
  wnLSF: number;
  dN: number;
  dtLSF: number;
  reserved3: number;
}
export interface MgaBdsIono {
  name: "MGA-BDS-IONO";
  type: number;
  version: number;
  reserved1: number;
  alpha0: number;
  alpha1: number;
  alpha2: number;
  alpha3: number;
  beta0: number;
  beta1: number;
  beta2: number;
  beta3: number;
  reserved2: number;
}
export interface MgaQzssEph {
  name: "MGA-QZSS-EPH";
  type: number;
  version: number;
  svid: number;
  reserved1: number;
  fitInterval: number;
  uraIndex: number;
  svHealth: number;
  tgd: number;
  iodc: number;
  toc: number;
  reserved2: number;
  af2: number;
  af1: number;
  af0: number;
  crs: number;
  deltaN: number;
  m0: number;
  cuc: number;
  cus: number;
  e: number;
  sqrtA: number;
  toe: number;
  cic: number;
  omega0: number;
  cis: number;
  crc: number;
  i0: number;
  omega: number;
  omegaDot: number;
  idot: number;
  reserved3: number;
}
export interface MgaQzssAlm {
  name: "MGA-QZSS-ALM";
  type: number;
  version: number;
  svid: number;
  svHealth: number;
  e: number;
  almWNa: number;
  toa: number;
  deltaI: number;
  omegaDot: number;
  sqrtA: number;
  omega0: number;
  omega: number;
  m0: number;
  af0: number;
  af1: number;
  reserve1: number;
}
export interface MgaQzssHealth {
  name: "MGA-QZSS-HEALTH";
  type: number;
  version: number;
  reserved1: number;
  healthCode: Buffer;
  reserved2: number;
}
export interface MgaGloEph {
  name: "MGA-GLO-EPH";
  type: number;
  version: number;
  svid: number;
  reserved1: number;
  FT: number;
  B: number;
  M: number;
  H: number;
  x: number;
  y: number;
  z: number;
  dx: number;
  dy: number;
  dz: number;
  ddx: number;
  ddy: number;
  ddz: number;
  tb: number;
  gamma: number;
  E: number;
  deltaTau: number;
  tau: number;
  reserved2: number;
}
export interface MgaGloAlm {
  name: "MGA-GLO-ALM";
  type: number;
  version: number;
  svid: number;
  reserved1: number;
  N: number;
  M: number;
  C: number;
  tau: number;
  epsilon: number;
  lambda: number;
  deltaI: number;
  tLambda: number;
  deltaT: number;
  deltaDT: number;
  H: number;
  omega: number;
  reserved2: number;
}
export interface MgaGloTimeoffset {
  name: "MGA-GLO-TIMEOFFSET";
  type: number;
  version: number;
  N: number;
  tauC: number;
  tauGps: number;
  B1: number;
  B2: number;
  reserved1: number;
}
export interface MgaAno {
  name: "MGA-ANO";
  type: number;
  version: number;
  svid: number;
  gnssId: number;
  year: number;
  month: number;
  day: number;
  reserved1: number;
  data: Buffer;
  reserved2: number;
}
export interface MgaFlashData {
  name: "MGA-FLASH-DATA";
  type: number;
  version: number;
  sequence: number;
  size: number;
  data: Buffer;
}
export interface MgaFlashAck {
  name: "MGA-FLASH-ACK";
  type: number;
  version: number;
  ack: number;
  reserved1: number;
  sequence: number;
}
export interface MgaFlashStop {
  name: "MGA-FLASH-STOP";
  type: number;
  version: number;
}
export interface MgaBdsPosXyz {
  name: "MGA-BDS-POS_XYZ";
  type: number;
  version: number;
  reserved1: number;
  ecefX: number;
  ecefY: number;
  ecefZ: number;
  posAcc: number;
}
export interface MgaBdsPosLlh {
  name: "MGA-BDS-POS_LLH";
  type: number;
  version: number;
  reserved1: number;
  lat: number;
  lon: number;
  alt: number;
  posAcc: number;
}
export interface MgaBdsTimeUtc {
  name: "MGA-BDS-TIME_UTC";
  type: number;
  version: number;
  ref: {
    source: number;
    fall: boolean;
    last: boolean;
  };
  leapSecs: number;
  year: number;
  month: number;
  day: number;
  hour: number;
  minute: number;
  second: number;
  reserved1: number;
  ns: number;
  tAccS: number;
  reserved2: number;
  tAccNs: number;
}
export interface MgaBdsTimeGnss {
  name: "MGA-BDS-TIME_GNSS";
  type: number;
  version: number;
  ref: {
    source: number;
    fall: boolean;
    last: boolean;
  };
  gnssId: number;
  reserved1: number;
  week: number;
  iTOW: number;
  ns: number;
  tAccS: number;
  reserved2: number;
  tAccNs: number;
}
export interface MgaBdsClkd {
  name: "MGA-BDS-CLKD";
  type: number;
  version: number;
  reserved1: number;
  clkD: number;
  clkDAcc: number;
}
export interface MgaBdsFreq {
  name: "MGA-BDS-FREQ";
  type: number;
  version: number;
  reserved1: number;
  flags: {
    source: number;
    fall: boolean;
  };
  freq: number;
  freqAcc: number;
}
export interface MgaBdsEop {
  name: "MGA-BDS-EOP";
  type: number;
  version: number;
  reserved1: number;
  d2kRef: number;
  d2kMax: number;
  xpP0: number;
  xpP1: number;
  ypP0: number;
  ypP1: number;
  dUT1: number;
  ddUT1: number;
  reserved2: Array<number>;
}
export interface MgaAck {
  name: "MGA-ACK";
  type: number;
  version: number;
  infoCode: number;
  msgId: number;
  msgPayloadStart: Buffer;
}
export interface MgaDbd {
  name: "MGA-DBD";
  reserved1: Array<number>;
  data: Buffer;
}
export interface MgaDbdPoll {
  name: "MGA-DBD";
  variant: "Poll";
}
export interface LogErase {
  name: "LOG-ERASE";
}
export interface LogString {
  name: "LOG-STRING";
  bytes: Buffer;
}
export interface LogCreate {
  name: "LOG-CREATE";
  version: number;
  logCfg: number;
  reserved1: number;
  logSize: number;
  userDefinedSize: number;
}
export interface LogInfo {
  name: "LOG-INFO";
  version: number;
  reserved1: number;
  filestoreCapacity: number;
  reserved2: number;
  currentMaxLogSize: number;
  currentLogSize: number;
  entryCount: number;
  oldestYear: number;
  oldestMonth: number;
  oldestDay: number;
  oldestHour: number;
  oldestMinute: number;
  oldestSecond: number;
  reserved3: number;
  newestYear: number;
  newestMonth: number;
  newestDay: number;
  newestHour: number;
  newestMinute: number;
  newestSecond: number;
  reserved4: number;
  status: number;
  reserved5: number;
}
export interface LogInfoPoll {
  name: "LOG-INFO";
  variant: "Poll";
}
export interface LogRetrieve {
  name: "LOG-RETRIEVE";
  startNumber: number;
  entryCount: number;
  version: number;
  reserved1: number;
}
export interface LogRetrievepos {
  name: "LOG-RETRIEVEPOS";
  entryIndex: number;
  lon: number;
  lat: number;
  hMSL: number;
  hAcc: number;
  gSpeed: number;
  heading: number;
  version: number;
  fixType: number;
  year: number;
  month: number;
  day: number;
  hour: number;
  minute: number;
  second: number;
  reserved1: number;
  numSV: number;
  reserved2: number;
}
export interface LogRetrievestring {
  name: "LOG-RETRIEVESTRING";
  entryIndex: number;
  version: number;
  reserved1: number;
  year: number;
  month: number;
  day: number;
  hour: number;
  minute: number;
  second: number;
  reserved2: number;
  byteCount: number;
  bytes: string;
}
export interface LogFindtime {
  name: "LOG-FINDTIME";
  version: number;
  type: number;
  reserved1: number;
  year: number;
  month: number;
  day: number;
  hour: number;
  minute: number;
  second: number;
  reserved2: number;
}
export interface LogFindtimeResponse {
  name: "LOG-FINDTIME";
  variant: "Response";
  version: number;
  type: number;
  reserved1: number;
  entryNumber: number;
}
export interface LogRetrieveposextra {
  name: "LOG-RETRIEVEPOSEXTRA";
  entryIndex: number;
  version: number;
  reserved1: number;
  year: number;
  month: number;
  day: number;
  hour: number;
  minute: number;
  second: number;
  reserved2: number;
  distance: number;
  reserved3: Array<number>;
}
export interface LogRetrievebatch {
  name: "LOG-RETRIEVEBATCH";
  version: number;
  flags: number;
  reserved0: number;
}
export interface LogBatch {
  name: "LOG-BATCH";
  version: number;
  contentValid: number;
  msgCount: number;
  iTOW: number;
  year: number;
  month: number;
  day: number;
  hour: number;
  min: number;
  sec: number;
  valid: number;
  tAcc: number;
  fracSec: number;
  fixType: number;
  flags: {
    bitsLow: number;
    psmState: number;
    reserved: number;
  };
  flags2: number;
  numSV: number;
  lon: number;
  lat: number;
  height: number;
  hMSL: number;
  hAcc: number;
  vAcc: number;
  velN: number;
  velE: number;
  velD: number;
  gSpeed: number;
  headMot: number;
  sAcc: number;
  headAcc: number;
  pDOP: number;
  reserved0: number;
  distance: number;
  totalDistance: number;
  totalStd: number;
  reserved1: number;
}
export interface SecSign {
  name: "SEC-SIGN";
  version: number;
  reserved1: number;
  msgId: number;
  checksum: number;
  hash: Buffer;
}
export interface SecUniqid {
  name: "SEC-UNIQID";
  version: number;
  reserved1: number;
  uniqueId: Buffer;
}
export interface SecUniqidPoll {
  name: "SEC-UNIQID";
  variant: "Poll";
}
export interface HnrPvt {
  name: "HNR-PVT";
  iTOW: number;
  year: number;
  month: number;
  day: number;
  hour: number;
  min: number;
  sec: number;
  valid: number;
  nano: number;
  fixType: number;
  flags: number;
  reserved1: number;
  lon: number;
  lat: number;
  height: number;
  hMSL: number;
  gSpeed: number;
  speed: number;
  headMot: number;
  headVeh: number;
  hAcc: number;
  vAcc: number;
  sAcc: number;
  headAcc: number;
  reserved2: number;
}
export interface HnrPvtPoll {
  name: "HNR-PVT";
  variant: "Poll";
}

export type UbxMessage =
  | NavPosecef
  | NavPosecefPoll
  | NavPosllh
  | NavPosllhPoll
  | NavStatus
  | NavStatusPoll
  | NavDop
  | NavDopPoll
  | NavAtt
  | NavAttPoll
  | NavSol
  | NavSolPoll
  | NavPvtUblox89
  | NavPvt
  | NavPvtPoll
  | NavOdo
  | NavOdoPoll
  | NavResetodo
  | NavVelecef
  | NavVelecefPoll
  | NavVelned
  | NavVelnedPoll
  | NavHpposecef
  | NavHpposecefPoll
  | NavHpposllh
  | NavHpposllhPoll
  | NavTimegps
  | NavTimegpsPoll
  | NavTimeutc
  | NavTimeutcPoll
  | NavClock
  | NavClockPoll
  | NavTimeglo
  | NavTimegloPoll
  | NavTimebds
  | NavTimebdsPoll
  | NavTimegal
  | NavTimegalPoll
  | NavTimels
  | NavTimelsPoll
  | NavSvinfo
  | NavSvinfoPoll
  | NavDgps
  | NavDgpsPoll
  | NavSbas
  | NavSbasPoll
  | NavOrb
  | NavOrbPoll
  | NavSat
  | NavSatPoll
  | NavGeofence
  | NavGeofencePoll
  | NavSvin
  | NavSvinPoll
  | NavRelposnedV1
  | NavRelposned
  | NavRelposnedPoll
  | NavSlas
  | NavSlasPoll
  | NavSig
  | NavSigPoll
  | NavAopstatus
  | NavAopstatusUblox8
  | NavAopstatusPoll
  | NavEoe
  | RxmRaw
  | RxmRawPoll
  | RxmSfrb
  | RxmSfrbx
  | RxmMeasx
  | RxmMeasxPoll
  | RxmRawx
  | RxmRawxPoll
  | RxmSvsi
  | RxmSvsiPoll
  | RxmAlm
  | RxmAlmPollSv
  | RxmAlmPoll
  | RxmEph
  | RxmEphPollSv
  | RxmEphPoll
  | RxmRtcm
  | RxmPmreqV0
  | RxmPmreq
  | RxmRlmLong
  | RxmRlmShort
  | RxmImes
  | RxmImesPoll
  | InfError
  | InfWarning
  | InfNotice
  | InfTest
  | InfDebug
  | AckNak
  | AckAck
  | CfgPrtDdc
  | CfgPrtUart
  | CfgPrtUsb
  | CfgPrtSpi
  | CfgPrtPortPoll
  | CfgPrtPoll
  | CfgMsg
  | CfgMsgCurrent
  | CfgMsgPoll
  | CfgInf
  | CfgInfPoll
  | CfgRst
  | CfgDat
  | CfgDatUser
  | CfgDatStandard
  | CfgDatPoll
  | CfgTp
  | CfgTpPoll
  | CfgRate
  | CfgRatePoll
  | CfgCfg
  | CfgFxn
  | CfgFxnPoll
  | CfgRxm
  | CfgRxmPoll
  | CfgEkf
  | CfgEkfPoll
  | CfgAnt
  | CfgAntPoll
  | CfgSbas
  | CfgSbasPoll
  | CfgNmeaV1
  | CfgNmeaV0
  | CfgNmea
  | CfgNmeaPoll
  | CfgUsb
  | CfgUsbPoll
  | CfgTmode
  | CfgTmodePoll
  | CfgOdo
  | CfgOdoPoll
  | CfgNvs
  | CfgNavx5
  | CfgNavx5
  | CfgNavx5
  | CfgNavx5Poll
  | CfgNav5
  | CfgNav5Poll
  | CfgTp5
  | CfgTp5PollSelect
  | CfgTp5Poll
  | CfgPm
  | CfgPmPoll
  | CfgRinv
  | CfgRinvPoll
  | CfgItfm
  | CfgItfmPoll
  | CfgPm2V2
  | CfgPm2
  | CfgPm2Poll
  | CfgTmode2
  | CfgTmode2Poll
  | CfgGnss
  | CfgGnssPoll
  | CfgLogfilter
  | CfgLogfilterPoll
  | CfgTxslot
  | CfgPwr
  | CfgHnr
  | CfgHnrPoll
  | CfgEsrc
  | CfgEsrcPoll
  | CfgDosc
  | CfgDoscPoll
  | CfgSmgr
  | CfgSmgrPoll
  | CfgGeofence
  | CfgGeofencePoll
  | CfgDgnss
  | CfgDgnssPoll
  | CfgTmode3
  | CfgTmode3Poll
  | CfgFixseed
  | CfgPms
  | CfgPmsPoll
  | CfgValset
  | CfgValget
  | CfgValgetPoll
  | CfgValdel
  | UpdSosRestored
  | UpdSosAck
  | UpdSosClear
  | UpdSosCreate
  | UpdSosPoll
  | MonIo
  | MonIoPoll
  | MonVer
  | MonVerPoll
  | MonMsgpp
  | MonMsgppPoll
  | MonRxbuf
  | MonRxbufPoll
  | MonTxbuf
  | MonTxbufPoll
  | MonHw
  | MonHwPoll
  | MonHw2
  | MonHw2Poll
  | MonRxr
  | MonPatch
  | MonPatchPoll
  | MonGnss
  | MonGnssPoll
  | MonSmgr
  | MonSmgrPoll
  | MonSpan
  | MonSpanPoll
  | MonComms
  | MonPatchPoll
  | MonHw3
  | MonHw3Poll
  | MonRf
  | MonRfPoll
  | AidReq
  | AidIni
  | AidIniPoll
  | AidHui
  | AidHuiPoll
  | AidData
  | AidAlm
  | AidAlmPollSv
  | AidAlmPoll
  | AidEph
  | AidEphPollSv
  | AidEphPoll
  | AidAlpsrv
  | AidAlpsrvToServer
  | AidAopUblox8
  | AidAop
  | AidAopPollSv
  | AidAopPoll
  | AidAlp
  | AidAlpStatus
  | AidAlpData
  | TimTp
  | TimTpPoll
  | TimTm2
  | TimTm2Poll
  | TimVrfy
  | TimVrfyPoll
  | TimSvin
  | TimSvinPoll
  | TimDosc
  | TimTos
  | TimSmeas
  | TimVcocal
  | TimVcocalExtended
  | TimVcocalStop
  | TimVcocalPoll
  | TimFchg
  | TimFchgPoll
  | EsfMeas
  | EsfMeasPoll
  | EsfRaw
  | EsfStatus
  | EsfStatusPoll
  | EsfIns
  | EsfInsPoll
  | MgaGpsEph
  | MgaGpsAlm
  | MgaGpsHealth
  | MgaGpsUtc
  | MgaGpsIono
  | MgaGalEph
  | MgaGalAlm
  | MgaGalTimeoffset
  | MgaGalUtc
  | MgaBdsEph
  | MgaBdsAlm
  | MgaBdsHealth
  | MgaBdsUtc
  | MgaBdsIono
  | MgaQzssEph
  | MgaQzssAlm
  | MgaQzssHealth
  | MgaGloEph
  | MgaGloAlm
  | MgaGloTimeoffset
  | MgaAno
  | MgaFlashData
  | MgaFlashAck
  | MgaFlashStop
  | MgaBdsPosXyz
  | MgaBdsPosLlh
  | MgaBdsTimeUtc
  | MgaBdsTimeGnss
  | MgaBdsClkd
  | MgaBdsFreq
  | MgaBdsEop
  | MgaAck
  | MgaDbd
  | MgaDbdPoll
  | LogErase
  | LogString
  | LogCreate
  | LogInfo
  | LogInfoPoll
  | LogRetrieve
  | LogRetrievepos
  | LogRetrievestring
  | LogFindtime
  | LogFindtimeResponse
  | LogRetrieveposextra
  | LogRetrievebatch
  | LogBatch
  | SecSign
  | SecUniqid
  | SecUniqidPoll
  | HnrPvt
  | HnrPvtPoll;

export declare class UbxParser {
  on(event: "message", listener: (msg: UbxMessage) => void): this;
  on(event: "ACK-ACK", listener: (msg: AckAck) => void): this;
  on(event: "ACK-NAK", listener: (msg: AckNak) => void): this;
  on(event: "AID-ALM", listener: (msg: AidAlm | AidAlmPollSv | AidAlmPoll) => void): this;
  on(event: "AID-ALP", listener: (msg: AidAlp | AidAlpStatus | AidAlpData) => void): this;
  on(event: "AID-ALPSRV", listener: (msg: AidAlpsrv | AidAlpsrvToServer) => void): this;
  on(event: "AID-AOP", listener: (msg: AidAopUblox8 | AidAop | AidAopPollSv | AidAopPoll) => void): this;
  on(event: "AID-DATA", listener: (msg: AidData) => void): this;
  on(event: "AID-EPH", listener: (msg: AidEph | AidEphPollSv | AidEphPoll) => void): this;
  on(event: "AID-HUI", listener: (msg: AidHui | AidHuiPoll) => void): this;
  on(event: "AID-INI", listener: (msg: AidIni | AidIniPoll) => void): this;
  on(event: "AID-REQ", listener: (msg: AidReq) => void): this;
  on(event: "CFG-ANT", listener: (msg: CfgAnt | CfgAntPoll) => void): this;
  on(event: "CFG-CFG", listener: (msg: CfgCfg) => void): this;
  on(event: "CFG-DAT", listener: (msg: CfgDat | CfgDatUser | CfgDatStandard | CfgDatPoll) => void): this;
  on(event: "CFG-DGNSS", listener: (msg: CfgDgnss | CfgDgnssPoll) => void): this;
  on(event: "CFG-DOSC", listener: (msg: CfgDosc | CfgDoscPoll) => void): this;
  on(event: "CFG-EKF", listener: (msg: CfgEkf | CfgEkfPoll) => void): this;
  on(event: "CFG-ESRC", listener: (msg: CfgEsrc | CfgEsrcPoll) => void): this;
  on(event: "CFG-FIXSEED", listener: (msg: CfgFixseed) => void): this;
  on(event: "CFG-FXN", listener: (msg: CfgFxn | CfgFxnPoll) => void): this;
  on(event: "CFG-GEOFENCE", listener: (msg: CfgGeofence | CfgGeofencePoll) => void): this;
  on(event: "CFG-GNSS", listener: (msg: CfgGnss | CfgGnssPoll) => void): this;
  on(event: "CFG-HNR", listener: (msg: CfgHnr | CfgHnrPoll) => void): this;
  on(event: "CFG-INF", listener: (msg: CfgInf | CfgInfPoll) => void): this;
  on(event: "CFG-ITFM", listener: (msg: CfgItfm | CfgItfmPoll) => void): this;
  on(event: "CFG-LOGFILTER", listener: (msg: CfgLogfilter | CfgLogfilterPoll) => void): this;
  on(event: "CFG-MSG", listener: (msg: CfgMsg | CfgMsgCurrent | CfgMsgPoll) => void): this;
  on(event: "CFG-NAV5", listener: (msg: CfgNav5 | CfgNav5Poll) => void): this;
  on(event: "CFG-NAVX5", listener: (msg: CfgNavx5 | CfgNavx5 | CfgNavx5 | CfgNavx5Poll) => void): this;
  on(event: "CFG-NMEA", listener: (msg: CfgNmeaV1 | CfgNmeaV0 | CfgNmea | CfgNmeaPoll) => void): this;
  on(event: "CFG-NVS", listener: (msg: CfgNvs) => void): this;
  on(event: "CFG-ODO", listener: (msg: CfgOdo | CfgOdoPoll) => void): this;
  on(event: "CFG-PM", listener: (msg: CfgPm | CfgPmPoll) => void): this;
  on(event: "CFG-PM2", listener: (msg: CfgPm2V2 | CfgPm2 | CfgPm2Poll) => void): this;
  on(event: "CFG-PMS", listener: (msg: CfgPms | CfgPmsPoll) => void): this;
  on(event: "CFG-PRT", listener: (msg: CfgPrtDdc | CfgPrtUart | CfgPrtUsb | CfgPrtSpi | CfgPrtPortPoll | CfgPrtPoll) => void): this;
  on(event: "CFG-PWR", listener: (msg: CfgPwr) => void): this;
  on(event: "CFG-RATE", listener: (msg: CfgRate | CfgRatePoll) => void): this;
  on(event: "CFG-RINV", listener: (msg: CfgRinv | CfgRinvPoll) => void): this;
  on(event: "CFG-RST", listener: (msg: CfgRst) => void): this;
  on(event: "CFG-RXM", listener: (msg: CfgRxm | CfgRxmPoll) => void): this;
  on(event: "CFG-SBAS", listener: (msg: CfgSbas | CfgSbasPoll) => void): this;
  on(event: "CFG-SMGR", listener: (msg: CfgSmgr | CfgSmgrPoll) => void): this;
  on(event: "CFG-TMODE", listener: (msg: CfgTmode | CfgTmodePoll) => void): this;
  on(event: "CFG-TMODE2", listener: (msg: CfgTmode2 | CfgTmode2Poll) => void): this;
  on(event: "CFG-TMODE3", listener: (msg: CfgTmode3 | CfgTmode3Poll) => void): this;
  on(event: "CFG-TP", listener: (msg: CfgTp | CfgTpPoll) => void): this;
  on(event: "CFG-TP5", listener: (msg: CfgTp5 | CfgTp5PollSelect | CfgTp5Poll) => void): this;
  on(event: "CFG-TXSLOT", listener: (msg: CfgTxslot) => void): this;
  on(event: "CFG-USB", listener: (msg: CfgUsb | CfgUsbPoll) => void): this;
  on(event: "CFG-VALDEL", listener: (msg: CfgValdel) => void): this;
  on(event: "CFG-VALGET", listener: (msg: CfgValget | CfgValgetPoll) => void): this;
  on(event: "CFG-VALSET", listener: (msg: CfgValset) => void): this;
  on(event: "ESF-INS", listener: (msg: EsfIns | EsfInsPoll) => void): this;
  on(event: "ESF-MEAS", listener: (msg: EsfMeas | EsfMeasPoll) => void): this;
  on(event: "ESF-RAW", listener: (msg: EsfRaw) => void): this;
  on(event: "ESF-STATUS", listener: (msg: EsfStatus | EsfStatusPoll) => void): this;
  on(event: "HNR-PVT", listener: (msg: HnrPvt | HnrPvtPoll) => void): this;
  on(event: "INF-DEBUG", listener: (msg: InfDebug) => void): this;
  on(event: "INF-ERROR", listener: (msg: InfError) => void): this;
  on(event: "INF-NOTICE", listener: (msg: InfNotice) => void): this;
  on(event: "INF-TEST", listener: (msg: InfTest) => void): this;
  on(event: "INF-WARNING", listener: (msg: InfWarning) => void): this;
  on(event: "LOG-BATCH", listener: (msg: LogBatch) => void): this;
  on(event: "LOG-CREATE", listener: (msg: LogCreate) => void): this;
  on(event: "LOG-ERASE", listener: (msg: LogErase) => void): this;
  on(event: "LOG-FINDTIME", listener: (msg: LogFindtime | LogFindtimeResponse) => void): this;
  on(event: "LOG-INFO", listener: (msg: LogInfo | LogInfoPoll) => void): this;
  on(event: "LOG-RETRIEVE", listener: (msg: LogRetrieve) => void): this;
  on(event: "LOG-RETRIEVEBATCH", listener: (msg: LogRetrievebatch) => void): this;
  on(event: "LOG-RETRIEVEPOS", listener: (msg: LogRetrievepos) => void): this;
  on(event: "LOG-RETRIEVEPOSEXTRA", listener: (msg: LogRetrieveposextra) => void): this;
  on(event: "LOG-RETRIEVESTRING", listener: (msg: LogRetrievestring) => void): this;
  on(event: "LOG-STRING", listener: (msg: LogString) => void): this;
  on(event: "MGA-ACK", listener: (msg: MgaAck) => void): this;
  on(event: "MGA-ANO", listener: (msg: MgaAno) => void): this;
  on(event: "MGA-BDS-ALM", listener: (msg: MgaBdsAlm) => void): this;
  on(event: "MGA-BDS-CLKD", listener: (msg: MgaBdsClkd) => void): this;
  on(event: "MGA-BDS-EOP", listener: (msg: MgaBdsEop) => void): this;
  on(event: "MGA-BDS-EPH", listener: (msg: MgaBdsEph) => void): this;
  on(event: "MGA-BDS-FREQ", listener: (msg: MgaBdsFreq) => void): this;
  on(event: "MGA-BDS-HEALTH", listener: (msg: MgaBdsHealth) => void): this;
  on(event: "MGA-BDS-IONO", listener: (msg: MgaBdsIono) => void): this;
  on(event: "MGA-BDS-POS_LLH", listener: (msg: MgaBdsPosLlh) => void): this;
  on(event: "MGA-BDS-POS_XYZ", listener: (msg: MgaBdsPosXyz) => void): this;
  on(event: "MGA-BDS-TIME_GNSS", listener: (msg: MgaBdsTimeGnss) => void): this;
  on(event: "MGA-BDS-TIME_UTC", listener: (msg: MgaBdsTimeUtc) => void): this;
  on(event: "MGA-BDS-UTC", listener: (msg: MgaBdsUtc) => void): this;
  on(event: "MGA-DBD", listener: (msg: MgaDbd | MgaDbdPoll) => void): this;
  on(event: "MGA-FLASH-ACK", listener: (msg: MgaFlashAck) => void): this;
  on(event: "MGA-FLASH-DATA", listener: (msg: MgaFlashData) => void): this;
  on(event: "MGA-FLASH-STOP", listener: (msg: MgaFlashStop) => void): this;
  on(event: "MGA-GAL-ALM", listener: (msg: MgaGalAlm) => void): this;
  on(event: "MGA-GAL-EPH", listener: (msg: MgaGalEph) => void): this;
  on(event: "MGA-GAL-TIMEOFFSET", listener: (msg: MgaGalTimeoffset) => void): this;
  on(event: "MGA-GAL-UTC", listener: (msg: MgaGalUtc) => void): this;
  on(event: "MGA-GLO-ALM", listener: (msg: MgaGloAlm) => void): this;
  on(event: "MGA-GLO-EPH", listener: (msg: MgaGloEph) => void): this;
  on(event: "MGA-GLO-TIMEOFFSET", listener: (msg: MgaGloTimeoffset) => void): this;
  on(event: "MGA-GPS-ALM", listener: (msg: MgaGpsAlm) => void): this;
  on(event: "MGA-GPS-EPH", listener: (msg: MgaGpsEph) => void): this;
  on(event: "MGA-GPS-HEALTH", listener: (msg: MgaGpsHealth) => void): this;
  on(event: "MGA-GPS-IONO", listener: (msg: MgaGpsIono) => void): this;
  on(event: "MGA-GPS-UTC", listener: (msg: MgaGpsUtc) => void): this;
  on(event: "MGA-QZSS-ALM", listener: (msg: MgaQzssAlm) => void): this;
  on(event: "MGA-QZSS-EPH", listener: (msg: MgaQzssEph) => void): this;
  on(event: "MGA-QZSS-HEALTH", listener: (msg: MgaQzssHealth) => void): this;
  on(event: "MON-COMMS", listener: (msg: MonComms) => void): this;
  on(event: "MON-GNSS", listener: (msg: MonGnss | MonGnssPoll) => void): this;
  on(event: "MON-HW", listener: (msg: MonHw | MonHwPoll) => void): this;
  on(event: "MON-HW2", listener: (msg: MonHw2 | MonHw2Poll) => void): this;
  on(event: "MON-HW3", listener: (msg: MonHw3 | MonHw3Poll) => void): this;
  on(event: "MON-IO", listener: (msg: MonIo | MonIoPoll) => void): this;
  on(event: "MON-MSGPP", listener: (msg: MonMsgpp | MonMsgppPoll) => void): this;
  on(event: "MON-PATCH", listener: (msg: MonPatch | MonPatchPoll | MonPatchPoll) => void): this;
  on(event: "MON-RF", listener: (msg: MonRf | MonRfPoll) => void): this;
  on(event: "MON-RXBUF", listener: (msg: MonRxbuf | MonRxbufPoll) => void): this;
  on(event: "MON-RXR", listener: (msg: MonRxr) => void): this;
  on(event: "MON-SMGR", listener: (msg: MonSmgr | MonSmgrPoll) => void): this;
  on(event: "MON-SPAN", listener: (msg: MonSpan | MonSpanPoll) => void): this;
  on(event: "MON-TXBUF", listener: (msg: MonTxbuf | MonTxbufPoll) => void): this;
  on(event: "MON-VER", listener: (msg: MonVer | MonVerPoll) => void): this;
  on(event: "NAV-AOPSTATUS", listener: (msg: NavAopstatus | NavAopstatusUblox8 | NavAopstatusPoll) => void): this;
  on(event: "NAV-ATT", listener: (msg: NavAtt | NavAttPoll) => void): this;
  on(event: "NAV-CLOCK", listener: (msg: NavClock | NavClockPoll) => void): this;
  on(event: "NAV-DGPS", listener: (msg: NavDgps | NavDgpsPoll) => void): this;
  on(event: "NAV-DOP", listener: (msg: NavDop | NavDopPoll) => void): this;
  on(event: "NAV-EOE", listener: (msg: NavEoe) => void): this;
  on(event: "NAV-GEOFENCE", listener: (msg: NavGeofence | NavGeofencePoll) => void): this;
  on(event: "NAV-HPPOSECEF", listener: (msg: NavHpposecef | NavHpposecefPoll) => void): this;
  on(event: "NAV-HPPOSLLH", listener: (msg: NavHpposllh | NavHpposllhPoll) => void): this;
  on(event: "NAV-ODO", listener: (msg: NavOdo | NavOdoPoll) => void): this;
  on(event: "NAV-ORB", listener: (msg: NavOrb | NavOrbPoll) => void): this;
  on(event: "NAV-POSECEF", listener: (msg: NavPosecef | NavPosecefPoll) => void): this;
  on(event: "NAV-POSLLH", listener: (msg: NavPosllh | NavPosllhPoll) => void): this;
  on(event: "NAV-PVT", listener: (msg: NavPvtUblox89 | NavPvt | NavPvtPoll) => void): this;
  on(event: "NAV-RELPOSNED", listener: (msg: NavRelposnedV1 | NavRelposned | NavRelposnedPoll) => void): this;
  on(event: "NAV-RESETODO", listener: (msg: NavResetodo) => void): this;
  on(event: "NAV-SAT", listener: (msg: NavSat | NavSatPoll) => void): this;
  on(event: "NAV-SBAS", listener: (msg: NavSbas | NavSbasPoll) => void): this;
  on(event: "NAV-SIG", listener: (msg: NavSig | NavSigPoll) => void): this;
  on(event: "NAV-SLAS", listener: (msg: NavSlas | NavSlasPoll) => void): this;
  on(event: "NAV-SOL", listener: (msg: NavSol | NavSolPoll) => void): this;
  on(event: "NAV-STATUS", listener: (msg: NavStatus | NavStatusPoll) => void): this;
  on(event: "NAV-SVIN", listener: (msg: NavSvin | NavSvinPoll) => void): this;
  on(event: "NAV-SVINFO", listener: (msg: NavSvinfo | NavSvinfoPoll) => void): this;
  on(event: "NAV-TIMEBDS", listener: (msg: NavTimebds | NavTimebdsPoll) => void): this;
  on(event: "NAV-TIMEGAL", listener: (msg: NavTimegal | NavTimegalPoll) => void): this;
  on(event: "NAV-TIMEGLO", listener: (msg: NavTimeglo | NavTimegloPoll) => void): this;
  on(event: "NAV-TIMEGPS", listener: (msg: NavTimegps | NavTimegpsPoll) => void): this;
  on(event: "NAV-TIMELS", listener: (msg: NavTimels | NavTimelsPoll) => void): this;
  on(event: "NAV-TIMEUTC", listener: (msg: NavTimeutc | NavTimeutcPoll) => void): this;
  on(event: "NAV-VELECEF", listener: (msg: NavVelecef | NavVelecefPoll) => void): this;
  on(event: "NAV-VELNED", listener: (msg: NavVelned | NavVelnedPoll) => void): this;
  on(event: "RXM-ALM", listener: (msg: RxmAlm | RxmAlmPollSv | RxmAlmPoll) => void): this;
  on(event: "RXM-EPH", listener: (msg: RxmEph | RxmEphPollSv | RxmEphPoll) => void): this;
  on(event: "RXM-IMES", listener: (msg: RxmImes | RxmImesPoll) => void): this;
  on(event: "RXM-MEASX", listener: (msg: RxmMeasx | RxmMeasxPoll) => void): this;
  on(event: "RXM-PMREQ", listener: (msg: RxmPmreqV0 | RxmPmreq) => void): this;
  on(event: "RXM-RAW", listener: (msg: RxmRaw | RxmRawPoll) => void): this;
  on(event: "RXM-RAWX", listener: (msg: RxmRawx | RxmRawxPoll) => void): this;
  on(event: "RXM-RLM", listener: (msg: RxmRlmLong | RxmRlmShort) => void): this;
  on(event: "RXM-RTCM", listener: (msg: RxmRtcm) => void): this;
  on(event: "RXM-SFRB", listener: (msg: RxmSfrb) => void): this;
  on(event: "RXM-SFRBX", listener: (msg: RxmSfrbx) => void): this;
  on(event: "RXM-SVSI", listener: (msg: RxmSvsi | RxmSvsiPoll) => void): this;
  on(event: "SEC-SIGN", listener: (msg: SecSign) => void): this;
  on(event: "SEC-UNIQID", listener: (msg: SecUniqid | SecUniqidPoll) => void): this;
  on(event: "TIM-DOSC", listener: (msg: TimDosc) => void): this;
  on(event: "TIM-FCHG", listener: (msg: TimFchg | TimFchgPoll) => void): this;
  on(event: "TIM-SMEAS", listener: (msg: TimSmeas) => void): this;
  on(event: "TIM-SVIN", listener: (msg: TimSvin | TimSvinPoll) => void): this;
  on(event: "TIM-TM2", listener: (msg: TimTm2 | TimTm2Poll) => void): this;
  on(event: "TIM-TOS", listener: (msg: TimTos) => void): this;
  on(event: "TIM-TP", listener: (msg: TimTp | TimTpPoll) => void): this;
  on(event: "TIM-VCOCAL", listener: (msg: TimVcocal | TimVcocalExtended | TimVcocalStop | TimVcocalPoll) => void): this;
  on(event: "TIM-VRFY", listener: (msg: TimVrfy | TimVrfyPoll) => void): this;
  on(event: "UPD-SOS", listener: (msg: UpdSosRestored | UpdSosAck | UpdSosClear | UpdSosCreate | UpdSosPoll) => void): this;
  on(event: string, listener: (...args: any[]) => void): this;
  feed(chunk: Uint8Array | Buffer): UbxMessage[];
  static parse(data: Uint8Array): UbxMessage[];
  static schema(): object[];
}

export declare class UbxLog {
  static open(filePath: string): Promise<UbxLog>;
  count(name?: string): number;
  messageTypes(): string[];
  next(name?: string): UbxMessage | null;
  prev(name?: string): UbxMessage | null;
  seek(pos: number): void;
  get(name: string, ordinal: number): UbxMessage | null;
  close(): void;
}
