#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const addon = require('bindings')('ubx-parser');

const schema = addon.schema();

// Convert name + variant to a PascalCase interface name
// e.g. name="NAV-PVT" variant="ublox-8/9" → "NavPvtUblox89"
function sanitizeName(name, variant) {
  const raw = variant ? `${name} ${variant}` : name;
  return raw
    .replace(/[()\/]/g, ' ')  // parens and slashes → spaces
    .replace(/[-_]+/g, ' ')   // dashes/underscores → spaces
    .trim()
    .split(/\s+/)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('')
    .replace(/[^A-Za-z0-9]/g, '');
}

// Convert a schema value to a TypeScript type string
function schemaToTs(val, indent) {
  if (typeof val === 'string') {
    // leaf types: "number", "string", "Buffer", "boolean", "null"
    return val;
  }

  if (typeof val !== 'object' || val === null) {
    return 'unknown';
  }

  // { "$array": elementSchema }
  if ('$array' in val) {
    const elemType = schemaToTs(val['$array'], indent);
    return `Array<${elemType}>`;
  }

  // { "$optional": innerSchema }
  if ('$optional' in val) {
    return schemaToTs(val['$optional'], indent) + ' | null';
  }

  // Nested object (Bundle / Bitfield)
  const keys = Object.keys(val);
  if (keys.length === 0) return '{}';

  const innerIndent = indent + '  ';
  const fields = keys.map(key => {
    const tsType = schemaToTs(val[key], innerIndent);
    return `${innerIndent}${key}: ${tsType};`;
  });

  return `{\n${fields.join('\n')}\n${indent}}`;
}

// Build all interfaces
const interfaces = [];
const typeNames = [];

for (let i = 0; i < schema.length; i++) {
  const msg = schema[i];
  const name = msg.name;
  const variant = msg.variant;
  const tsName = sanitizeName(name, variant);
  typeNames.push(tsName);

  const fieldKeys = Object.keys(msg.fields);
  const fieldLines = fieldKeys.map(key => {
    const tsType = schemaToTs(msg.fields[key], '  ');
    return `  ${key}: ${tsType};`;
  });

  let body = `  name: ${JSON.stringify(name)};\n`;
  if (variant) {
    body += `  variant: ${JSON.stringify(variant)};\n`;
  }
  body += fieldLines.join('\n') + (fieldLines.length ? '\n' : '');

  interfaces.push(
    `export interface ${tsName} {\n` + body + `}`
  );
}

// Build output
const lines = [
  '// Auto-generated by scripts/generate-types.js — do not edit manually',
  `// Generated from ${schema.length} UBX message definitions`,
  '',
  ...interfaces,
  '',
  `export type UbxMessage =\n  | ${typeNames.join('\n  | ')};`,
  '',
  'export function parse(data: Uint8Array): UbxMessage[];',
  'export function schema(): object[];',
  '',
];

const outPath = path.join(__dirname, '..', 'types.d.ts');
fs.writeFileSync(outPath, lines.join('\n'));
console.log(`Written ${outPath} (${schema.length} message types)`);
